### ISSUE TITLE
add support for nuki-extended adapter devices

### ISSUE THREAD

**Issue by aortmannm** [ciddi89/ioBroker.device-watcher#11]
Hi,

probably it's possible to add nuki-extended adapter. There are different things that can be connected to the nuki bridge and I have two of them.

One of the devices has just the batteryCritical State and one has batter berrtyChargeState with the percentage.

![image](https://user-images.githubusercontent.com/3414298/172398802-d866ca27-ee94-4f51-9a78-d90783379e5a.png)

**Comment by ciddi89** [comment]
Can you give me the whole path of batteryChargeState, please? Then I will look if I get it implemented.

**Comment by aortmannm** [comment]
The Lock:
```
nuki-extended.0.smartlocks.schloss.state.batteryChargeState
```

The Opener:
```
nuki-extended.0.openers.opener.state.batteryCritical
```

But the 'opener' and 'schloss' in the object path is the name of my device so this will change for different persons and locks.

**Comment by ciddi89** [comment]
Yes okay thanks. I will look the next days. The opener doesn't have the state batteryChargeState?

**Comment by ciddi89** [comment]
Okay I added Nuki Extended. But we have to test if it works. I have to lookout for the datapoint batteryCritical. Otherwise it will not work. I hope the timestamp of this datapoint is refreshing sometimes so it will not shown as an offline device. Maybe you can try it and tell me
