### ISSUE TITLE
Please support HomeConnect

### ISSUE THREAD

**Issue by Standarduser** [ciddi89/ioBroker.device-watcher#110]
**Which adapter should be implement:**
iobroker.homeconnect
https://github.com/iobroker-community-adapters/ioBroker.homeconnect

**The following information is important to add the adapter correctly, if possible add a json or screenshot with the information:**
Every HomeConnect device has a connected state, e.g.
`homeconnect.0.SIEMENS-SX758X06TE-68A40E117A96.general.connected`
`homeconnect.0.SIEMENS-TI9575X9FU-68A40E57624D.general.connected`
None of the other states (update, battery,...) are available.

<img width="1810" alt="Bildschirmfoto 2023-01-07 um 15 16 14" src="https://user-images.githubusercontent.com/8029204/211155359-c572e32d-8eff-44db-b070-8a0e3828163b.png">

Thanx in advance

**Comment by ciddi89** [comment]
Done! Will be available in next adapter version. If you like to test it, you can install the GitHub version.
