### ISSUE TITLE
Please support SmartGarden

### ISSUE THREAD

**Issue by Standarduser** [ciddi89/ioBroker.device-watcher#111]
**Which adapter should be implement:**
iobroker.smartgarden
https://github.com/jpgorganizer/ioBroker.smartgarden

**The following information is important to add the adapter correctly, if possible add a json or screenshot with the information:**
There are different types of smart garden devices, such as mower, sprinkler, sensors, ... Depending on the type of device not all states make sense. In my case, a mower, only online state makes sense, because the mower is moving what results to an empty battery within an hour. But sensor devices should have the others too. At the moment I just can deliver states of my mower.

<img width="1820" alt="Bildschirmfoto 2023-01-07 um 15 13 33" src="https://user-images.githubusercontent.com/8029204/211155549-dacc7ac4-dea1-464a-a286-662fda333519.png">

Thanx in advance

**Comment by ciddi89** [comment]
Who the hell is putting the id in the names of channel? 🤯 

Well it's not your fault and the work is done. Adapter will be available in next version or you try out the GitHub version.
