### ISSUE TITLE
Support Tuya-Adapter

### ISSUE THREAD

**Issue by reutli** [ciddi89/ioBroker.device-watcher#112]
Since Apollon made the new Tuya-Adapter ready for local devices it would be greta to have the devices covered by your project!

**Comment by ciddi89** [comment]
Do you have a screenshot with an example device? Need the path for battery, rssi/link quality, connected etc. if available.

**Comment by AdamK-DE** [comment]
here are some.. i just installed the device-watcher and no tuya support aviable ?!?! :((((((((((((((((((((

Temp Sensor / Zigbee over TUYA Gateway:
![Unbenannt-1](https://user-images.githubusercontent.com/127183545/223348929-9511d7f3-d299-40cc-b7a7-b421affb7f0e.png)

MOES 4 Scene Switch / Zigbee over TUYA Gateway:
![Unbenannt-2](https://user-images.githubusercontent.com/127183545/223349033-a988bb5b-e558-4793-921c-f2c4802dd6aa.png)

Zigbee PIR over TUYA Zigbee Gateway:
![Unbenannt-3](https://user-images.githubusercontent.com/127183545/223349166-c4356e53-f42b-436b-a823-da119e7da2c8.png)

Door Sensor over Zigbee TUYA Gateway:
![Unbenannt-4](https://user-images.githubusercontent.com/127183545/223349238-5e75bc25-8404-432a-97e1-5bf1b5e95f0c.png)

**Comment by AdamK-DE** [comment]
and a TUYA/SmartLife WIFI SmartPlug:

![Unbenannt-5](https://user-images.githubusercontent.com/127183545/223351170-f8f27aab-3bda-47b1-b73c-2634b77e56e5.png)

**Comment by AdamK-DE** [comment]
i will send tuya ZIGBEE smartplug tomorrow :)

**Comment by AdamK-DE** [comment]
TUYA Zigbee SmartPlug:

![Unbenannt-6](https://user-images.githubusercontent.com/127183545/223678801-98d2a45f-aed6-4951-805d-ecedcaebbcfb.png)

**Comment by ciddi89** [comment]
Das problem hier ist das ich normalerweise die Werte über die id's finde. Hier bei tuya sind das aber fast nur irgendwelche willkürlichen Zahlen. Ich muss mir daher erst eine neue Strategie ausdenken ob ich das über die Rollen machen kann oder so.

**Comment by reutli** [comment]
is actual, no close

**Comment by Ilovegym66** [comment]
> Das problem hier ist das ich normalerweise die Werte über die id's finde. Hier bei tuya sind das aber fast nur irgendwelche willkürlichen Zahlen. Ich muss mir daher erst eine neue Strategie ausdenken ob ich das über die Rollen machen kann oder so.

Hi, ich habe ueber 130 Tuya-Devices, hier ist immer der Datenpunkte tuya.0.*.online true/false, also darauf kann man zu 99% triggern.. 
Bei Zigbee-Tuya-Devices ueber das Gateway gibt es keinen Datenpunkt, zumindest bei meinen nicht. Hier kann man hochstens das Gateway selbst triggern.

Ein Versuch waere es Wert.. :-) 
Und den Namen des Devices aus dem Namen auswerten, nicht aus der ID.. :-)

**Comment by ciddi89** [comment]
Danke @Ilovegym66 werde es die Tage mal mit reinnehmen zum Testen

**Comment by ciddi89** [comment]
Mit 2.9.6 wird der online Status bei Tuya Geräten, falls vorhanden, unterstützt.

**Comment by Ilovegym66** [comment]
Funktioniert, super, danke !☺️

**Comment by ciddi89** [comment]
Super! Wenn sich noch mehr Möglichkeiten bieten einfach Bescheid geben. :)
