### ISSUE TITLE
Shelly Firmwareupdate messages are sent every few seconds

### ISSUE THREAD

**Issue by firebowl** [ciddi89/ioBroker.device-watcher#114]
The option to be informed about firmware updates is great. Unfortunately, for my Shelly devices, I get the message every few seconds (if there really is an update) until I have performed the update.

Device-Manager Version: 2.3.0
Node.js: v16.19.0
NPM: 8.19.3

PS: Great job on how quickly new device types are supported!

**Comment by ciddi89** [comment]
Thanks for your report.I know already what's the problem. Will fix it later. 🙌🏻

**Comment by ciddi89** [comment]
should be fix now

**Comment by firebowl** [comment]
Lol, fast as Lightning ;)
Thank you, will test it.

**Comment by ciddi89** [comment]
You can try the GitHub version. Or you wait few days. I have to fix another thing and if it works I will push a new release.

**Comment by firebowl** [comment]
GitHub version is fine for me. Is the fix included in 2.4.0?

**Comment by ciddi89** [comment]
yes, install the adapter over expert settings and paste the link under custom url https://github.com/ciddi89/ioBroker.device-watcher
