### ISSUE TITLE
Multiple Messages

### ISSUE THREAD

**Issue by ciddi89** [ciddi89/ioBroker.device-watcher#115]
**Describe the bug**  
In case of zigbee, zigbee2mqtt etc. the adapter sends online and offline messages of each device if the connection to the main device(zigbee stick, zigbee2mqtt container etc.) is lost.

**To Reproduce**  
1. In my case : reboot or update the zigbee2mqtt container
2. messages of each device will be send.

**Expected behavior**  
No messages or only one message of that the connection is lost.

**Versions:**  
 - Adapter version: 2.4.0

**Comment by Day1983** [comment]
The same by myside.
Update top 2.4, and i get Lot of Messages.

Hue devices, Connect or Not connected. But i have select "only Batterie devices", and geht states-Messages from Hue devices (Lights).

![Screenshot_2023-01-11-21-11-28-92_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/77491820/211909189-a583f67d-f524-4c05-804f-3b0f51f123a5.jpg)

**Comment by ciddi89** [comment]
@Day1983 danke für dein Hinweis. Werde beides prüfen. Passiert das bei dir auch wenn der adapter gestoppt/gestartet oder geupdatet wird? Hab schon zu 50% eine lösung…

**Comment by Day1983** [comment]
Guten Morgen, 
Erstmal vielen Dank an Dich, dass Du dir überhaupt die Mühe und Zeit nimmst, einen Adapter zur Verfügung zu stellen.

Heute morgen hab ich in Telegramm 80 Mitteilungen.🤣

Die Meldungen kommen quer Beet... Heute Nacht hat die Fritzbox reboot gemacht, somit haben sich dann alle WLAN Dosen gemeldet.
Obwohl ich nur Batterie angegeben habe.

Vielen Dank.

**Comment by ciddi89** [comment]
Gerne, mittlerweile ist es doch ziemlich komplex geworden, und desto mehr User das nutzen, desto mehr Fehler tauchen auch :D 

Das mit den 80 mitteilen sollte natürlich nicht sein. Wenn sich Geräte nur kurz mal abmelden und anmelden dann muss man bisschen mit den Zeiten in den Experten Einstellungen spielen. Das muss jeder für sich herausfinden. 

Darf ich fragen um welche Geräte es sich bei dir handelt? Evtl. Shelly? Dafür hat ein anderer Entwickler in den Shelly adapter einen neuen Datenpunkt hinzugefügt da es sonst unmöglich war den als battery device zu identifizieren. Wenn das so ist, Musst du glaub ich die Github Version von Shelly installieren. Weiss nicht ob es dafür schon ein offizielles update gab.

**Comment by Day1983** [comment]
Logo darfst du fragen,
Es sind Lampen aus Hue Adapter, sonoff WLAN Steckdosen, und zig Mal auf dem Homematic ein Fensterkontakt mit Batterie, ( stündlich).

Eigentlich sind es alle die devices, die ich nicht haben will, weil ich ja nur Batterie betrieben haben möchte. Alle mit 230V will ich ja gar nicht 😉

**Comment by ciddi89** [comment]
@Day1983 okay, da war ein fehler drin. Nun sollten bei dir auch wirklich nur batterie Geräte angezeigt werden. Könntest du es evtl testen indem du in iobroker unter Adapter auf Experten Einstellungen gehst, auf die Katze und dann bei Benutzerdefiniert den link einfügt und installierst?  
https://github.com/ciddi89/ioBroker.device-watcher

**Comment by Day1983** [comment]
Warum kommen den für jeden devices eine separate Meldung? War das nicht vorher als Liste in einer einzigen Meldung?

Aber alle Geräte sind Batterie.... (Neustart Zigbee Adapter hat die Meldungen ausgelöst)
![Screenshot_2023-01-12-19-25-59-63_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/77491820/212148852-d00e7d0c-235d-4dbc-bb6d-87ffe5303d1a.jpg)

**Comment by ciddi89** [comment]
Ah shit, hatte zur Kontrolle für mich ein debug log mit eingebaut. Nehme ich gleich raus. 

Ähm ja genau vorher war das als Liste. Ziel für die Zukunft war aber das die Liste nur noch an einen gewünschten Zeitpunkt gesendet wird und die Geräte nur einzeln dann wenn das jeweilige Gerät auch online oder offline geht. Ich arbeite derzeit daran das irgendwie weg zu bekommen das wenn die Instanz oder der Stick ausfällt oder wieder startet, alle Geräte nacheinander gesendet werden. Damit man nicht vollgespamt wird. Ä

**Comment by ciddi89** [comment]
So log warn message ist gelöscht. 
Bisher hatte ich es auch nur geschafft die Nachrichten nicht zu senden wenn das device, also der Hauptstick, nicht connected ist. Wenn er wieder neu verbunden ist, ist schwer zu lösen. aber werde die tage was finden. So oft fällt dieser ja nicht aus. zumindest bei mir.

**Comment by Day1983** [comment]
Du bist der Beste!

**Comment by ciddi89** [comment]
Ich habe nun eine Funktion eingebaut das erst geprüft wird ob der state change des Datenpunkt info.connection (wenn es denn diesen gibt) länger als paar Sekunden her ist und wenn ja, dann werden erst nachrichten gesendet. Das soll eine Welle von Nachrichten auf einmal verhindern wenn zb. die Verbindung zum Stick verloren geht oder die Instanz neu startet. Konnte das bisher aber nur an Zigbee2mqtt testen. Wäre cool wenn du das mal bei dir mit den Zigbee adapter testen kannst.

**Comment by Day1983** [comment]
Sorry für die späte Antwort.
Ich hab den Adapter (ohne Update) neugestartet und es sind viele Meldungen gekommen (Batterie betriebe, nicht erreichbar, dann wieder erreichbar).

Dann über GitHub das Update gemacht (über die Katze).
Dann wieder neu start Adapter, leider wieder die gleichen Meldungen, wie vorher.

Danke Dir.

**Comment by ciddi89** [comment]
Alles gut. :)
hmm okay. Vielleicht muss ich dann die Zeit erhöhen.
