### ISSUE TITLE
Mobile Alerts Adapter

### ISSUE THREAD

**Issue by MicGei** [ciddi89/ioBroker.device-watcher#122]
Mobile Alerts Adapter

https://github.com/bluerai/ioBroker.mobile-alerts/blob/master/README.md

**Comment by ciddi89** [comment]
Brauche mehr Information darüber. Am besten eine Auflistung und die Struktur der Datenpunkte von einem Beispiel Gerät.

**Comment by MicGei** [comment]
Beim Mobile Alerts System handelt es sich hauptsächlich um günstige Temperatur- , Regen-,  Luftfeuchte- und Windsensoren, die über ein Gateway verbunden sind.
Man kann die Date auch über eine Website des Unternehmens individuell abrufen:
(z.B. https://measurements.mobile-alerts.eu/Home/SensorsOverview?phoneid= (hier muß noch die PhoneID aus der Handy App eingetragen werden)).
Ich habe mal Bilder von ioBroker Objektbaum geschickt. Hoffentlich hilft das (bin leider Laie).
Weitere Infos:
https://github.com/bluerai/ioBroker.mobile-alerts/blob/master/README.md
https://github.com/bluerai/ioBroker.mobile-alerts
https://mobile-alerts.eu/de/home/
Vielen Dank für das Interesse!

**Comment by MicGei** [comment]
Beim Mobile Alerts System handelt es sich hauptsächlich um günstige Temperatur- , Regen-,  Luftfeuchte- und Windsensoren, die über ein Gateway verbunden sind.
Man kann die Date auch über eine Website des Unternehmens individuell abrufen:
(z.B. https://measurements.mobile-alerts.eu/Home/SensorsOverview?phoneid= (hier muss noch die PhoneID aus der Handy App eingetragen werden)).
Ich habe mal Bilder von ioBroker Objektbaum geschickt. Hoffentlich hilft das (bin leider Laie).
Weitere Infos:
https://github.com/bluerai/ioBroker.mobile-alerts/blob/master/README.md
https://github.com/bluerai/ioBroker.mobile-alerts
https://mobile-alerts.eu/de/home/
Vielen Dank für das Interesse!

**Comment by ciddi89** [comment]
Hallo, 
Danke für die Info. Leider werden Bilder per Email nicht mitgeschickt. Wäre cool wenn du diese nachträglich über die GitHub Seite hinzufügen kannst. Das würde mir ungemein helfen beim hinzufügen des Adapters.

**Comment by MicGei** [comment]
Ich habs versucht!

**Comment by ciddi89** [comment]
#127
