### ISSUE TITLE
Please support Proxmox

### ISSUE THREAD

**Issue by Standarduser** [ciddi89/ioBroker.device-watcher#123]
**Which adapter should be implement:**
ioBroker.proxmox
https://github.com/iobroker-community-adapters/ioBroker.proxmox

**The following information is important to add the adapter correctly, if possible add a json or screenshot with the information:**
Der Proxmox-Adapter erzeugt unterschiedliche Arten von Channels, die je nach Typ, auf ihren Online-Status überwacht werden könnten.
1. LXC-Container
    - Der Channelname beginnt immer mit `lxc_`
    - Können daraufhin überwacht werden, ob sie laufen oder nicht
    - Der zu überwachende Datenpunkt heißt `proxmox.0.lxc_xxx.status`
    - Wert für "gut": `running`
2. Knoten
    - Der Channelname beginnt immer mit `node_`
    - Können daraufhin überwacht werden, ob sie laufen oder nicht
    - Der zu überwachende Datenpunkt heißt `proxmox.0.node_xxx.status`
    - Wert für "gut": `online`
3. Virtuelle Maschinen
    - Der Channelname beginnt immer mit `qemu_`
    - Können daraufhin überwacht werden, ob sie laufen oder nicht
    - Der zu überwachende Datenpunkt heißt `proxmox.0.qemu_xxx.status`
    - Wert für "gut": `running`
4. Speicher
    - Der Channelname beginnt immer mit `storage_`
    - Eine Überwachung über diesen Adapter macht meiner Ansicht nach keinen Sinn

**Additional context**
Danke :)

**Comment by ciddi89** [comment]
Proxmox has been added and will be available in future versions.
