### ISSUE TITLE
Instanzüberwachung: NINA funktioniert nicht

### ISSUE THREAD

**Issue by Standarduser** [ciddi89/ioBroker.device-watcher#126]
Es scheint ein Problem mit ioBroker.nina zu geben.
https://github.com/TA2k/ioBroker.nina

Obwohl der NINA-Adapter vollkommen unauffällig läuft, meldet Device-Watcher per Telegram, dass die Instanz einen Fehler hätte:
`Fehler einer Instanz entdeckt: nina.0: not connected to Device`. Diese Meldung kommt regelmäßig aller 5-10 Minuten mehrfach (siehe Issue #124).

Dieses Verhalten kann ich an der Instanz so jedoch nicht beobachten und ein Script, das auf die Datenpunkte `system.adapter.nina.0.alive` und `system.adapter.nina.0.connected` triggert, meldet dieses Problem nicht.

Außerdem ignoriert der Adapter, dass NINA für Benachrichtigungen geblacklistet ist. Das Ausschließen aus Listen scheint hingegen zu funktionieren.

**Comment by ciddi89** [comment]
Leider kann ich bis jetzt dein Issue nicht reproduzieren. Das einzige was bei mir vorkommt das kurz nach adapterstart von Nina der Datenpunkt Nina.0.info.connected einmal kurz auf false geht und wieder auf true. Aber das auch nur einmal.
 
Habe aber schon die letzten Tage diverse Änderungen ohne release gemacht. Daher: 
- Bitte installier mal über die Katze und füge den link https://github.com/ciddi89/ioBroker.device-watcher bei benutzerdefiniert ein. Habe schon einige Sachen gefixed. 
- Wenn das problem weiterhin besteht schau bitte unter Nina.0.info.connected ob sich der Datenpunkt in den Abständen einmal auf false und dann wieder auf true meldet. 
Kurze Erklärung wie das ganze läuft:  Es wird geprüft ob die Datenpunkte alive, host connected und device connected (falls verfügbar) alle true sind, wenn alive false ist, wird die Instanz sofort auf deaktiviert gesetzt. Ansonsten wenn device oder host auf false ist, wird 10 Sekunden gewartet, nochmal geprüft, wenn es immer noch sie wird nochmal 10 Sekunden gewartet und erst dann wird die Instanz auf Fehler gesetzt. Hatte mir das aus einen anderen Skript abeguckt und fand das verfahren dafür ziemlich gut und zuverlässig. Das sollte also heissen das der device connected Datenpunkt länger auf false sein müsste. 

Das problem mit der Blacklist ist in der Github Version behoben.

**Comment by Standarduser** [comment]
Dein Hinweis, den Datenpunkt `nina.0.info.connection` zu beobachten, war sehr hilfreich. Tatsächlich scheint der mehrfach auf `false` zu wechseln.

Macht es Sinn, auch hier nach 10 Sekunden erneut zu prüfen, ob der Zustand noch immer `false` ist?

**Comment by ciddi89** [comment]
Der wird schon mit geprüft. Wie lange ist der denn auf false? Ist das in der GitHub version auch noch der Fall? Kann sonst höchsten die Zeit erhöhen.

```

			case 'daemon':
				if (!isAlive) return ['Instance deactivated', false, null]; // if instance is turned off
				if (isDeviceConnected === undefined) isDeviceConnected = true;
				// In case of (re)start, connection may take some time. We take 3 attempts.
				// Attempt 1/3 - immediately
				if (isHostConnected && isDeviceConnected) {
					isHealthy = true;
					instanceStatusString = 'Instance okay';
				} else {
					// Attempt 2/3 - after 10 seconds
					await this.wait(10000);
					if (isHostConnected && isDeviceConnected) {
						isHealthy = true;
						instanceStatusString = 'Instance okay';
					} else {
						// Attempt 3/3 - after 20 seconds in total
						await this.wait(10000);
						if (isHostConnected && isDeviceConnected) {
							isHealthy = true;
							instanceStatusString = 'Instance okay';
						} else {
							if (!isDeviceConnected) {
								instanceStatusString = 'not connected to Device';
								isHealthy = false;
							} else if (!isHostConnected) {
								instanceStatusString = 'not connected to host';
								isHealthy = false;
							}
						}
					}
				}
				break;

```

**Comment by Standarduser** [comment]
Ich habe die Version installiert, die du vor 3 Stunden hochgeladen hast.
Mein Script liefert folgendes (Objekt-ID, Value, aktuelle Zeit):
`nina.0.info.connection false 17:48:26.920`
`nina.0.info.connection true 17:48:26.977`

Die Meldung `Fehler einer Instanz entdeckt: nina.0: not connected to Device` kam nur ein paar Sekunden später.

**Comment by ciddi89** [comment]
Ok ja bei mir kam nun auch einmal die Meldung. Werde ich die Tage noch mal prüfen woran das liegen könnte. Kann aber vielleicht erstmal n bisschen dauern, da für die kommende Woche die Zeit leider n bisschen knapp ist. 🙈

**Comment by Standarduser** [comment]
Kein Thema, die Blacklist funktioniert ja nun hervorragend 😁

**Comment by ciddi89** [comment]
Hatte irgendwie ein Denkfehler in der Funktion. Die States wurden nur am Anfang der Funktion geladen aber nicht aktualisiert wenn sich diese doch während des Timers wieder veränderten. Habe das nun gefixed und in meinen Tests kamen diesbezüglich keine Fehlfunktion mehr vor. Hoffe das bleibt auch so. :)

**Comment by Standarduser** [comment]
>   Kurze Erklärung wie das ganze läuft:  Es wird geprüft ob die Datenpunkte alive, host connected und device connected (falls verfügbar) alle true sind, wenn alive false ist, wird die Instanz sofort auf deaktiviert gesetzt. Ansonsten wenn device oder host auf false ist, wird 10 Sekunden gewartet, nochmal geprüft, wenn es immer noch sie wird nochmal 10 Sekunden gewartet und erst dann wird die Instanz auf Fehler gesetzt. 

Ich möchte gerne nochmal auf diesen Punkt zurückkommen. Wäre es nicht vielleicht sinnvoll, wenn man ähnlich wie bei den Devices einstellen könnte, wie lange ein Adapter gestört sein muss, bis die Meldung kommt?

Diese Nacht habe ich zwei mal innerhalb einer Minute die Meldung bekommen, dass der Telegram-Adapter ein Problem hätte. Das Logfile zeigt nichts dazu an, insofern ist das schwer nachvollziehbar. Es scheint mir so, als würden sich unterschiedliche Adapter auch unterschiedlich verhalten, was ja nicht unbedingt auf einen Fehler im Adapter zurückzuführen ist, sondern u.U. auf das, was der Adapter als Bedingung voraussetzt, dass er connected auf true setzt.

Ich denke das würde auch deinen Support-Aufwand erheblich reduzieren, wenn man diese Einstellung frei wählen könnte.

**Comment by ciddi89** [comment]
Ja bei telegram ist ja die Besonderheit das es jede Nacht neu startet, wenn man es nicht deaktiviert hat.

Hmm ich würde sonst erstmal eine Möglichkeit schaffen das man die Zeit für die Instanzen allgemein sich einstellen kann wie lange dieser Fehler anstehen soll bis dieser sich als Fehler meldet. 
Oder 
Ich gebe die Zeit vor im Code so wie jetzt und setze diese noch etwas höher.
