### ISSUE TITLE
re: Mobile Alerts

### ISSUE THREAD

**Issue by MicGei** [ciddi89/ioBroker.device-watcher#127]
Beim Mobile Alerts System handelt es sich hauptsächlich um günstige Temperatur- , Regen-,  Luftfeuchte- und Windsensoren, die über ein Gateway verbunden sind.
Man kann die Date auch über eine Website des Unternehmens individuell abrufen:
(z.B. https://measurements.mobile-alerts.eu/Home/SensorsOverview?phoneid= (hier muss noch die PhoneID aus der Handy App eingetragen werden)).
 
Ich habe mal Bilder von ioBroker Objektbaum geschickt. Hoffentlich hilft das (bin leider Laie).
 
Weitere Infos:
https://github.com/bluerai/ioBroker.mobile-alerts/blob/master/README.md
https://github.com/bluerai/ioBroker.mobile-alerts
https://mobile-alerts.eu/de/home/
 
 
Vielen Dank für das Interesse!

![Mobile Alerts](https://user-images.githubusercontent.com/123824297/215352298-140497e9-f10e-4518-aa03-88a444ff0ee9.JPG)
![Mobile Alerts 2](https://user-images.githubusercontent.com/123824297/215352306-b1cbdd9e-a36b-42e9-8785-1768077e1f9d.JPG)

**Comment by ciddi89** [comment]
Danke, werde ich mir die tage angucken ob ich da was machen kann. Wird aber aktuell evtl. ein bisschen dauern. :)

**Comment by ciddi89** [comment]
Hallo @MicGei,

sorry das es so lang dauert. Hab es mir eben angeguckt. Was soll man aber beobachten bei dem Adapter? Es gibt keine Battery/Link Quality werte. Das einzige was man beobachten könnte wäre den Datenpunkt Zeitpunkt für die Indikation ob ein Gerät offline oder online ist. Aber dafür muss ich wissen ob sich die Zeitstempel regelmäßig aktualisieren bzw. nicht mehr aktualisieren wenn das Gerät tatsächlich nicht erreichbar ist. 

Ich danke dir schon mal

**Comment by MicGei** [comment]
Hallo Christian, 

danke für die Rückmeldung. Die Zeitstempel werden regelmäßig aktualisiert. Grundsätzlich wird in der dazugehörigen App auf dem Handy auch angezeigt, wenn die Batterien schwach werden. Im Adapter gibt es das aber leider wirklich nicht. Der ist leider recht einfach aufgebaut.
Wenn das Ganze aber halt nicht machbar ist, ist das auch nicht schlimm. 

Vielen Dank für Deine Bemühungen. 

p.s.: Ich antworte erst jetzt, da ich bis heute im Urlaub war.
