### ISSUE TITLE
FHEM TFA Sensors

### ISSUE THREAD

**Issue by hoehnem** [ciddi89/ioBroker.device-watcher#137]
Please add Sensors for Instance TFA (866 MHz) temperature and/or humidity, which are connected via FHEM to iobroker.

**Comment by ciddi89** [comment]
Hi, thanks for your feature / adapter request. Please give me some more information. The best way is to post a screenshot with an example device where I can find important datapoints like connected/battery/RSSI/link quality etc.

**Comment by hoehnem** [comment]
Hi Christian,

 

 

First many thanks for your adapter and your excellent work. Very fast response. 

 

I’m not so familiar with Github and to  posting there, so I send you the requested information directly via Mail . Should I publish this information also on Github itself? If you need additional information, please let me know. 

 

I’m using FHEM installed native on a x86 device and in iobroker the FHEM adapter

 



 

I have checked  if I see differences in batteryState . The picture below shows only state false, but und FHEM itself I see 

 



 

There are also other informations, but not in iobroker for instance RSSI

 



 

 

 

 

 



 

 

Here is a TFA sensor in FHEM with battery state low and in iobroker  it is  a “true “ state. 

 





 

Wir können auch auf Deutsch schreiben 😊

 

 

Gruß Marcel 

 

 

 

 

 

Von: Christian Behrends ***@***.***> 
Gesendet: Dienstag, 14. Februar 2023 19:38
An: ciddi89/ioBroker.device-watcher ***@***.***>
Cc: hoehnem ***@***.***>; Author ***@***.***>
Betreff: Re: [ciddi89/ioBroker.device-watcher] FHEM TFA Sensors (Issue #137)

 

Hi, thanks for your feature / adapter request. Please give me some more information. The best way is to post a screenshot with an example device where I can find important datapoints like connected/battery/RSSI/link quality etc.

**Comment by hoehnem** [comment]
![image](https://user-images.githubusercontent.com/79630947/218967280-8d082c38-2308-484e-96ac-552caa735cf7.png)
![image](https://user-images.githubusercontent.com/79630947/218972690-ee0d7a75-2ecb-430f-b6f2-77c4d6b518e1.png)

Der Batterystate wechselt zwischen "true" = low(FHEM) und "false" = ok(FHEM) Die Aktualisierung ist bei mir ca. 2,5 Minuten .Es ist ein Mindesteventintervall(FHEM)  bei den Sensoren von 5 Minuten eingestellt. 

![image](https://user-images.githubusercontent.com/79630947/218973502-46ff7517-1609-44f9-afcc-a1721738802b.png)
