### ISSUE TITLE
FHEM TFA Sensoren in Version 2.61 

### ISSUE THREAD

**Issue by hoehnem** [ciddi89/ioBroker.device-watcher#145]
Hi Christian,

vielen Dank für die superschnelle Umsetzung , der TFA Adapter Integration. Leider konnte ich das jetzt erst ausprobieren , da ich technische Probleme hatte . Es gibt da noch ein "Schönheitsproblem" Hier mal ein Screenshot aus dem Grafana Dashboard 

![image](https://user-images.githubusercontent.com/79630947/223461212-bad007be-4338-4bc0-b300-e64e835f0246.png)

Der Online Status wird nicht richtig angezeigt und die Darstellung "Last contact" zeigt die Zeit seit dem letzten Start des Adapters bzw. des IObrokers. Ich gehe davon aus, daß das der Timestamp des letzten Empfangs sein müßte und dann auch der Online Status funktioniert. 

Batteriestatus ist soweit richtig.

Nochmals vielen Dank

**Comment by ciddi89** [comment]
Kannst du mir denn ein Datenpunkt nennen wo der Zeitstempel immer recht aktuell sind? Dann ändere ich das ab. :)

**Comment by hoehnem** [comment]
Moin,

reicht das ?

![image](https://user-images.githubusercontent.com/79630947/223518554-122fc853-8348-4837-b95b-b7ba4914fc69.png)

**Comment by ciddi89** [comment]
Ja werde mal morgen oder übermorgen das abändern :)

**Comment by ciddi89** [comment]
Ich habe nun den Datenpunkt 'state' für die zeit Ermittlung genommen. Haben alle Sensoren diesen Datenpunkt?

**Comment by hoehnem** [comment]
Moin Christian,
habe das geprüft. Ja alle Sensoren bei mir haben diesen Datenpunkt.

**Comment by ciddi89** [comment]
Super passt dann ja. Die GitHub version hat das dann bereits. Ansonsten auf das nächste offizielle Update warten :)

**Comment by ciddi89** [comment]
Will be fixed in v2.7.0
