### ISSUE TITLE
Possibility to ignore 0 values for battery

### ISSUE THREAD

**Issue by boergegrunicke** [ciddi89/ioBroker.device-watcher#162]
**Is your feature request related to a problem? Please describe.**
In my zigbee network there are some devices, that deliver sporadically 0% for battery value. Especially the Aqara Opple Wall switches are doint this from time to time. But one device may send a useful percentage on one day, and on another day just 0. This produces a lot of "wrong positive" warnings and makes me ignore all the battery warnings.

**Describe the solution you'd like**
As usually no battery level should jump from 20 to 0, and option to ignore just 0 as value for battery would be nice. It must not be enabled by default, but having the possibility would be very nice.

**Comment by ciddi89** [comment]
Hi @boergegrunicke 

Ich habe es nun so eingestellt das das Gerät vorher einen Wert von unter 5 haben muss damit er bei 0 reagiert. Ansonsten alles was darüber ist und er springt dann auf 0 wird es ignoriert. So sollten die Fehlerhaften Meldungen ausbleiben.
