### ISSUE TITLE
Please support LOQED adapter

### ISSUE THREAD

**Issue by Standarduser** [ciddi89/ioBroker.device-watcher#163]
**Which adapter should be implement:**
LOQED Smart Lock
https://github.com/foxriver76/ioBroker.loqed

**The following information is important to add the adapter correctly, if possible add a json or screenshot with the information:**
- Has the adapter/device a battery state?
Yes: `loqed.0.lockStatus.batteryPercentage`

- Has the adapter/device an lowbat state?
No.

- Has the adapter/device an RSSI or link quality state?
No, it's implemented in connected state.

- Has the adapter/device a connected/reachable state?
Yes: `loqed.0.info.connection`
This state is true if lock is connected (also regarding the link quality)

- Has the adapter/device an update/upgrade state?
No.

- What is the best datapoint, which is refreshing frequently the timestamp?
None. Datapoints are only updated when the lock changes it's lock/unlock state or on adapter start.

**Additional context**
You need one instance for each device

**Comment by ciddi89** [comment]
I @Standarduser I implemented it. But we have to look if it gets the right name. Maybe you can try It and if is something wrong please feel free to contact me. thanks
