### ISSUE TITLE
Many notifications if an instanz goes on and off

### ISSUE THREAD

**Issue by SurfGargano** [ciddi89/ioBroker.device-watcher#168]
**Describe the bug**  
If a device goes on and off many times in a short delay , device watcher send many notifications.
I have seen with the broadlink adapter, that the system tried to start the instanz , it goes fail and the system try to start again and so on. 
Every time a notification was send.
Also on javascript or other adapters.

It is possible to define a general timeout for all instances ?
So that the first time the notification was send immediately , but when an event occurs within the timeout, no notification should be send.

I know , that I can define a time out for each instance, but not for all globally.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
only one time notification 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: V2.8.0
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by ciddi89** [comment]
Thanks for your suggestion. I will add an option for the user to change the time global.

**Comment by SurfGargano** [comment]
Ok, thx. 
In the case there is an individual time out, this individual time out should be preferred.

**Comment by ciddi89** [comment]
@SurfGargano it should work with v2.8.1
