### ISSUE TITLE
Dauernde Push Nachrichten, Instanz falsch

### ISSUE THREAD

**Issue by SurfGargano** [ciddi89/ioBroker.device-watcher#170]
**Describe the bug**  
Obwohl in globaler Fehlerzeit 300 Sekunden eingetragen ist, wird alle paar Sekunden eine PushOver Nachricht gesendet, wenn eine Instanz deaktiviert ist.
Außerdem ist die Instanz falsch.
Instanz Mielecloudservice ist deaktiviert, gemeldet wird Meteoalarm, obwohl Meteoalarm aktiv ist.

Objekt device-watcher.0.adapterAndInstances.listDeactivatedInstances:
[{"Adapter":"Mielecloudservice","Instance":"mielecloudservice.0","Status":"Instanz deaktiviert"}]

Objekt device-watcher.0.lastNotification :
Instanz Watchdog:
meteoalarm.0: Instance deactivated

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
Erst nach Verstreichen der globalen (oder individuellen) Fehlerzeit sollte eine Nachricht kommen und dann nur einmal. 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <2.8.1>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by ciddi89** [comment]
Naja zu Punkt 1.:
- Fehlerzeit ist nicht gleich Deaktivierzeit. Die Dinge werden verschieden gehandhabt. Bei Fehlerzeit gilt die Zeit die man im Adapter eingetragen hat. Zeit für deaktivieren ist derzeit noch nicht möglich. Eigentlich deaktiviert man Adapter händisch, daher sah ich da noch keine Notwendigkeit für. 

Punkt 2.: sicher das dein meteoalarm Adapter rund läuft? Ich werde später mal den Adapter installieren und versuchen den Fehler zu reproduzieren. Aber irgendwas scheint da nicht richtig zu laufen wenn er alle paar Sekunden die Nachricht sendet.

**Comment by ciddi89** [comment]
Mit v2.8.2 besteht nun auch die Möglichkeit zu definieren, wann ein Adapter als Deaktiviert gelten soll.

Zum Thema Meteocloud wird gemeldet obwohl ein anderer Dienst deaktiviert wird muss man noch mal gucken warum das so ist falls dies immer noch der Fall ist. Eigentlich ist Meteocloud ein Schedule Adapter und sollte daher sowieso nur in der Aktiv Liste auftauchen außer der Devicewatcher erkennt das er seine letzte Schedule operation nicht durchgeführt hat, dann gilt er erst als deaktiviert.

**Comment by SurfGargano** [comment]
Das mit Meteoalarm hat sich wahrscheinlicih erledigt, da war irgend etwas faul. Hat auch nicht richtig funktioniert.
Ich habe den Meteoalarm Adapter neu installiert. Jetzt geht der Meteoalarm richtig. Ich melde mich wenn es noch etwas zu Meckern gibt. Ansonsten schließe ich den Issue.

**Comment by ciddi89** [comment]
Alles gut, freut mich wenn es nun läuft

**Comment by ciddi89** [comment]
Naja habe schon selbst gemerkt das ich da noch mal ein bisschen Nacharbeiten muss. Irgendwie haut das noch nicht so hin wie ich es mir wünsche. Bei Instanzen die keine Datenpunkte is connected to device haben läuft das leider noch nicht rund. Werde das aber so bald wie möglich fixen

**Comment by ciddi89** [comment]
Okay, Fehler gefunden. Habe was wichtiges in den abfragen vergessen. Werde gleich v2.8.3 releasen damit sollten die Dauernde Push nachrichten definitiv weg bleiben

**Comment by SurfGargano** [comment]
Hab nun die V2.8.3 ausprobiert. Seltsamerweise war jetzt Cron eingestellt. (?)
Da ich schon mal Probleme beim Update hatte, habe ich den Adapter gelöscht und neu installiert.
Da ist das Cron jetzt weg.
Aber so richtig gehts es  nicht. Ich habe den LGTV Adapter, der ist dann nicht connected wenn das Gerät aus ist.

- Alarm wird alle 20 Sekunden gemeldet.
- Mielecloud mag er gar nicht, da wird gar keine keine Meldung gesendet bei Disabled (Pushover), pbwohl alive = false ist.
- Blacklist lässt sich nicht mehr editieren, es wird keine oder nur eine unvollständige Auswahlliste angezeigt. 

Nodejs V18.15
NPM V9.5.0
Admin V6.4.3

**Comment by ciddi89** [comment]
Hmm das ist alles wirklich sehr merkwürdig. Habe alles ausgiebig getestet und es lief alles so wie es soll. Werde mal im Forum nach Haken ob da noch jemand Probleme hat. Leider bist du bisher der einzige. 

Wegen den Cron: Werte sind erstmal alle default auf false. Bis der User was es ändert und speichert. Ich selber kann per Update nur über grosse Umwege was ändern. 

Ist der mielecloud Adapter ein Typ deamon Adapter? Es gibt noch andere Typen die aber selten sind. Bisher werden nur deamon und schedule unterstützt. 

Wie gesagt muss erstmal nach Haken ob noch jemand Probleme hat. Ich konnte selber keine mehr feststellen.

**Comment by ciddi89** [comment]
Aaaalso habe noch ein bisschen rum probiert und habe glaube ich einen Adapter gefunden der ähnlich reagiert. Das Hauptproblem wird sein das die Datenpunkte alive, connected usw. wahrscheinlich alle paar Sekunden auf true gehen und dann wieder auf false. Ich werde versuchen eine Lösung dafür zu finden und werde mich dann wieder melden wenn ich was gefunden habe.

**Comment by SurfGargano** [comment]
Kann es sein, daß zum Aufbau der Auswahllisten der Adapter laufen muß und es eine Zeitlang dauert, bis alle Adapter zu sehen sind ?
Das ist wohl das Problem, daß ich nach dem Install keine Instanzen  oder Devices zum Auswählen sehe. Z.B. in der Blacklist

**Comment by SurfGargano** [comment]
Beim restart vom Device-Watcher habe ich dann noch diese Meldung : 
`
host.raspberrypi | 2023-04-15 14:46:18.670 | info | instance system.adapter.device-watcher.0 started with pid 1507228
host.raspberrypi | 2023-04-15 14:46:16.217 | info | instance system.adapter.device-watcher.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
device-watcher.0 | 2023-04-15 14:46:16.105 | error | uncaught exception: Connection is closed.
host.raspberrypi | 2023-04-15 14:46:15.488 | info | stopInstance system.adapter.device-watcher.0 send kill signal
`

**Comment by ciddi89** [comment]
Ja genau, der Adapter muss dafür laufen um die benötigte Informationen abzufragen und um diese dann in einem Array zu schreiben. Leider ist das nicht anders möglich. Abhängig vom System wie leistungsfähig es ist kann es manchmal sein das es ein bisschen rum zickt. Liegt aber nicht an dem Adapter sondern am Admin Interface.

**Comment by SurfGargano** [comment]
Wäre gut , wenn da ein Hinweis aufklappen würde, wenn der Adapter nicht läuft und man die Listen Editieren will. So sucht man etwas vergeblich.

**Comment by ciddi89** [comment]
Soo Ich habe die Funktionen für die Statuserkennung der Instanzen einmal komplett gelöscht und neu geschrieben mit neuer Logik. Es sollte nun auf jeden fall besser laufen. (Ich hoffe es!! :D ) Dauernde Meldung blieben bisher bei mir aus. Evtl. Muss man nun aber einmal die Blacklist und Zeitenliste für Instanzen neu ausfüllen wenn man diese ausgefüllt hatte. 

Außerdem erscheint nun eine PopUp Meldung wenn die Instanz nicht läuft aber man versucht eine neue Zeile auszuwählen bei den Tabellen in den Einstellungen.

<img width="1387" alt="Screenshot 2023-04-16 at 16 10 09" src="https://user-images.githubusercontent.com/66088020/232321117-6b3be146-7f02-4b0e-ad2f-6f18adf5e517.png">

**Comment by SurfGargano** [comment]
Sieht mit der letzten Version auf Github ok aus.
