### ISSUE TITLE
Instanzen-Blacklist nicht mehr editierbar

### ISSUE THREAD

**Issue by SurfGargano** [ciddi89/ioBroker.device-watcher#172]
**Describe the bug**  
Trotz laufender Instanz ist die Instanzen-Blacklist nicht mehr editierbar.
Angezeigt wird die Liste, aber beim Auswählen kommt dann diese Meldung
![image](https://user-images.githubusercontent.com/70272783/232416246-4a9c055d-7fd9-467d-9ffb-f1d999861dc9.png)
 
Ich habe auch den Adapter neu installiert, gleiches Ergebnis.

Die anderen Auswahllisten funktionieren.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.8.4
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by ciddi89** [comment]
Hm dann liegt es am Admin. Ich kann es auf jeden Fall nicht reproduzieren. Mal abwarten ob sich sonst noch jemand meldet mit dem Problem dann nehme ich das wieder raus. 

BTW: die Listen können trotzdem erstellt werden. Einfach auf verstanden gehen und auswählen dann. Ist nur nervig wenn man auf das + klickt oder die Mülltonne wenn es immer wieder aufploppt. 

Aber sicher das sonst alles rund läuft? Das passt nämlich zum Bild das er manchmal bei dir den Text dann nicht richtig in den Auswahl Menüs anzeigt was du in den anderen issue erwähnt hast. Ergo heißt es das der Adapter öfters mal neu startet?

**Comment by SurfGargano** [comment]
Adapter startet nicht öfters neu. nur nach dem Speichern der Konfiguration.

Ist ja nur bei den Instanzen Blacklist so, bei Geräte/Dienste geht es ja.
Außerdem ist ja die Meldung richtig, wenn ich auf '+' drücke und die Instanz läuft nicht.
Nur kommt zusätzlich beim Auswählen auch die Meldung und es werden keine Instanzen eingetragen.

Also bei mir ist das so : 
Adapter läuft und eine Zeit gewartet.
Dann unter Blacklist/Instanzen auf '+' drücken.
Auswahlliste wird angezeigt.
Bei Drücken auf eine Instanz in der Liste kommt dann die Meldung 
Beim Drücken auf 'Verstanden' oder 'Abbrechen' schließt die Meldung, aber eingetragen wird nichts.

Also nur die Meldung beim Auswählen der Blacklist-Instanzen rausnehmen.

Ich habe noch nicht alles getestet, da die Blacklist nicht geht.

**Comment by SurfGargano** [comment]
Funktioniert jetzt
