### ISSUE TITLE
Checkbox für Senden ' Instanz ok'

### ISSUE THREAD

**Issue by SurfGargano** [ciddi89/ioBroker.device-watcher#173]
**Is your feature request related to a problem? Please describe.**
Wenn innerhalb der Deaktivierungs- oder Fehlerzeit die Instanz deaktiviert und dann wieder aktiviert wird, kommt die Nachricht 'Instanz ok'
Kannst Du da eine globale Checkbox und für jede eingetragene separate Instanz (Wählen Sie aus, welche Instanzen eine längere Ausfallzeit haben sollen) machen, damit diese Meldung nicht mehr kommt ?
Die separate Einstellung soll die globale überschreiben.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ciddi89** [comment]
Eigentlich ist das vorgesehen das dann **garkeine** Nachricht kommen soll wenn die Instanz wieder läuft / ok ist. Werde das nochmal prüfen.

**Comment by ciddi89** [comment]
Habe zwar keine Checkbox mit eingebaut aber dafür bleibt die Nachricht 'Instanz ok' nun aus wenn die Instanz kurzzeitig deaktiviert und wieder aktiviert wird. Ich bin noch am Überlegen ob ich generell mit reinnehmen soll das eine Nachricht gesendet wird wenn die wieder vollkommen okay ist. Aber weiß noch nicht ob ich das mache.
