### ISSUE TITLE
Zigbee2mqtt offline Devices 

### ISSUE THREAD

**Issue by david883** [ciddi89/ioBroker.device-watcher#186]
**Describe the bug**  
Hallo, mir ist aufgefallen das Zigbee Geräte über den Adapter zigbee2mqtt nicht im Datenpunkt device-watcher.0.offlineList
auftauchen. Benachrichtigung das ein Gerät offline ist bekomme ich aber darüber.

**Versions:**  
 - Adapter version: 2.9.1
 - JS-Controllee Version:

Plattform:
linux
Betriebssystem:
linux
Architektur:
x64
CPUs:
4
Geschwindigkeit:
2500 MHz
Modell:
Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
RAM:
6 GB
System-Betriebszeit:
63 T. 07:05:11
Node.js:
v16.20.0
time:
1685380631745
Adapter-Anzahl:
474
NPM:
8.19.4
Datenträgergröße:
31.2 GB
Freier Festplattenspeicher:
16.6 GB
Betriebszeit:
32 T. 00:38:50
Aktive Instanzen:
31
Pfad:
/opt/iobroker/
aktiv:
_nodeCurrent:
16.20.0
_nodeNewest:
16.20.0
_nodeNewestNext:
16.20.0
_npmCurrent:
8.19.4
_npmNewest:
8.19.4
_npmNewestNext:
8.19.4

**Comment by ciddi89** [comment]
Danke fürs issue erstellen. Man verliert das sonst aus den Augen wenn man paar Tage was anderes zu tun hatte 😀 
Habe auch gleich fragen um damit ich versuchen kann das zu reproduzieren:

- Tritt es nur bei bestimmten Geräten/Adaptern auf oder bei allen?

- welche Zeiten hast du unter expert Settings für die Geräte wo der Fehler auftritt?

Ich danke schon mal für die Infos

**Comment by david883** [comment]
Tritt es nur bei bestimmten Geräten/Adaptern auf oder bei allen?

Bisher habe ich es nur beim Zigbee2mqtt  Adapter bemerkt.

welche Zeiten hast du unter expert Settings für die Geräte wo der Fehler auftritt?

10 Minuten

Allerdings ist zu bedenken daß batteriebetriebene Zigbee Geräte über den zigbee2mqtt Adapter erst nach 24h und Geräte mit Stromversorgung nach 15 Minuten offline gemeldet werden. (Einstellung zigbee2mqtt Server)

**Comment by david883** [comment]
Bitte schließen. Adapter komplett neu aufgesetzt und Datenpunkte geändert.
