### ISSUE TITLE
Tasmota device offline / online -> no reliable notification telegram

### ISSUE THREAD

**Issue by slimline33** [ciddi89/ioBroker.device-watcher#191]
**Describe the bug**  
I am getting either no offline or no online notification on Tasmota devices. Have already tested everything from reinstalling, changed Telegram settings through. Waiting time turned up to 1 to 5 minutes....

Alexa, Unifi, Zigbee work as usual. In the offline overview is the offline Tasmota device then.

The Tasmota adapter switches the alive status 100% to false or true depending on the state.

When I get an offline message, then I get mostly no online message.

**To Reproduce**  
1. Unplug Tasmota flashed Plug
2. Wait for Message
3. Wait some minutes
4. Plug the Tasmota plug back into the socket, in offline overview the plug disappears again, but the notification remains off.

**Screenshots & Logfiles**  

![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/3323812/e645e271-8932-4a43-ba78-1830288b1147)

![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/3323812/5c639c26-59fb-458d-ac20-a58029c78d66)

![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/3323812/fd829555-f2e1-42bc-bebe-3e9f815b5d73)

![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/3323812/0c3fb5af-e9ae-49b8-8f8f-c001d37131f9)

**Versions:**  
 - Adapter version: 2.9.1
 - JS-Controller version: 4.0.24
 - Node version: v16.19.1
 - Operating system: Debian

**Comment by ciddi89** [comment]
Hi, sorry für die späte Antwort. Hab in letzter Zeit viel um die Ohren. :) 

Hmm das ist wirklich komisch. Haben die Tasmota Geräte denn einen uptime Datenpunkt? Passiert das auch wenn beim device watcher in den Experten Einstellungen die Zeit auf 0 steht?
