### ISSUE TITLE
Zuletzt Gesehen stimmt beim Ping-Adapter nicht

### ISSUE THREAD

**Issue by Standarduser** [ciddi89/ioBroker.device-watcher#192]
Wenn ein mit Ping überwachtes Gerät offline geht, dann stimmt die bei Zuletzt Gesehen angezeigte Zeit nicht.
Scheinbar wird der Zeitstempel der letzten Aktualisierung des Datenpunktes angezeigt, statt der letzten Änderung.

<img width="793" alt="Bildschirmfoto 2023-06-09 um 20 10 02" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/8029204/ecbe9677-52bb-4a14-bead-c06bd2f679c7">

<img width="396" alt="Bildschirmfoto 2023-06-09 um 20 13 10" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/8029204/e54b36c5-ab76-49c5-8d7c-3f9c61fad30b">

(Die Screenshots wurden zeitlich leicht versetzt gemacht)

**Comment by ciddi89** [comment]
Thx für die Info. Werde es dieses we korrigieren. :)

**Comment by ciddi89** [comment]
Should be fixed with next version
