### ISSUE TITLE
Liste mit Error Instanzen wird nicht aktualisiert

### ISSUE THREAD

**Issue by MarkSau** [ciddi89/ioBroker.device-watcher#194]
Beide States "device-watcher.0.adapterAndInstances.listInstancesError" und "device-watcher.0.adapterAndInstances.HTML_Lists.listInstancesErrorHTML" werden nicht aktualisierst, wenn die Instance wieder ok ist.
Nur ein Neustart der device-watcher instanz behebt das. Falls danach eine Instanz wieder einen Fehler hat und danach OK meldet, belibt der Status "Error" bestehen.
Als Beispiel, nach einem Iobroker Neustart z.B., habe ich den Deye Adapter, der eine Weile braucht bis er alles Daten vom Wechselrichter gesammelt hat und zeigt deshalb für einige Minuten an, dass er nicht mit dem Gerät verbunden ist. Nachdem er dann wieder grün wird, wechseln die o.g. States aber nicht die Meldung.
![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/22911084/3384f6a0-b47a-4298-a264-9ef486b83f7d)
device-watcher.0.adapterAndInstances.listInstancesError: [{"Adapter":"Deyeidc","Instance":"deyeidc.0","Mode":"daemon","Status":"Nicht verbunden mit Gerät oder Dienst"}]

**Comment by ciddi89** [comment]
Hallo,
sorry für die späte Antwort habe aber in letzter Zeit viel um die Ohren. Erstmal die Frage welche Version ist installiert? Weisst du ob es bei anderen Adapter auch zu diesen Fehler kommt? Habe versucht das nach zu stellen aber leider konnte ich bissher nichts finden da bei mir alles wie erwartet funktioniert. Daher müssen wir mal schritt für schritt auf Fehlersuche gehen.

**Comment by MarkSau** [comment]
Hi,,
ich habe derzeit Version 2.9.2 installiert.
Im Moment wird gerade die Instanz [{"Adapter":"Fb-checkpresence","Instance":"fb-checkpresence.0","Mode":"daemon","Status":"Nicht verbunden mit Gerät oder Dienst"}] bemängelt.
Die Instanz ist aber grün.

**Comment by MarkSau** [comment]
Eine Gemeinsamkeit haben die Instanzen.  Das kann aber auch Zufall sein.
Sie laufen auf dem Slave und nicht auf dem Master.

**Comment by ciddi89** [comment]
> Eine Gemeinsamkeit haben die Instanzen.  Das kann aber auch Zufall sein.
> 
> Sie laufen auf dem Slave und nicht auf dem Master.

Guter Hinweis. Das könnte ein Ansatzpunkt sein. Ich gucke mal was da für Unterschiede sind und warum er dann evtl. nicht richtig läuft.

**Comment by ciddi89** [comment]
Fehler sollte mit nächster Version gefixed sein.
