### ISSUE TITLE
Zigbee TuYa Thermostat has only batterLow indicator

### ISSUE THREAD

**Issue by o0shojo0o** [ciddi89/ioBroker.device-watcher#20]
**Is your feature request related to a problem? Please describe.**
The TuYa TS0601_thermostat (Zigbee) does not output the battery state in % or volt but only batterLow indicator.
[More Information](https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html#battery-low-binary)   

**Describe the solution you'd like**
Solution like Zwave or Homematic

**Additional context**
```json
{
  "type": "state",
  "common": {
    "name": "Battery Status Low",
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator.lowbat",
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "storageType": "",
        "aliasId": "",
        "changesOnly": true,
        "debounce": 0,
        "changesRelogInterval": 60,
        "changesMinDelta": 0,
        "retention": "63072000",
        "maxLength": 10
      }
    }
  },
  "native": {},
  "_id": "zigbee.0.847127fffe11df7a.battery_low",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1630530366536
}
```
![image](https://user-images.githubusercontent.com/19333515/181587825-edc01345-65af-4fd6-8aed-afc52468ccae.png)

**Comment by ciddi89** [comment]
thanks for your reference. I added the state `.battery_low` for Zigbee devices. Please check if it's working for you now.

**Comment by o0shojo0o** [comment]
Thanks for the quick implementation, it works as expected.

**Comment by o0shojo0o** [comment]
Wouldn't it be correct for a lowBat device to show the Battery state instead of 
` "Battery": " - ",` 
better 
` "Battery": "ok",` 
` "Battery": "low",`
?
Here is an example of how it is now :
```json
    {
        "Device": "GB.Sensor.Thermostat",
        "Adapter": "Zigbee",
        "Battery": " - ",
        "Signal strength": "33%",
        "Last contact": "01:32 Uhr",
        "Status": "Online"
    },
```
Also, the lowbat does not appear in the battery devices list.

**Comment by ciddi89** [comment]
Done :)

**Comment by o0shojo0o** [comment]
Thanks again for your quick implementation, do I need to enable anything else to have the low or ok states in the lists?
