### ISSUE TITLE
Verständnisfrage offline Meldungen

### ISSUE THREAD

**Issue by freaktech** [ciddi89/ioBroker.device-watcher#202]
^leider blocke ich nicht ganz durch wann eine Gerät als offline gemeldet wird (im laufe des Tages)

ich bekomme immer wieder Meldungen, Gerät offline und 1 Min später sofort Gerät ist wieder erreichbar.

Welche Zeit schlägt da zu?
Immer wenn ich nachsehe sind diese aber online,

diese Meldung ergebt doch keinen Sinn?
Noch dazu is das ein shelly und ich hab doch eingestellt min 60 Minuten offline ?!?

![361244885_10224031681689616_6129691500191823456_n](https://github.com/ciddi89/ioBroker.device-watcher/assets/33237257/cb7570dd-7ea2-4fdd-b592-c7dd3fed42c5)

![2023-07-17 08_40_42-](https://github.com/ciddi89/ioBroker.device-watcher/assets/33237257/8517301f-ae04-4e1c-b3cf-cbf7e091d56c)

danke

**Comment by ciddi89** [comment]
Hmm das ergibt wirklich keinen Sinn. Für die Zeit nimmt er den Datenpunkt uptime, wann dieser zuletzt aktualisiert wurde. Ist dieses Verhalten auch wenn du die Zeit mal länger oder kürzer einstellst? Scheint das die Zeit nicht greift und er den Datenpunkt connected nimmt falls dieser sich mal kurz von true auf false ändert.

**Comment by freaktech** [comment]
ja auch mit anderen Werte, vorher war 5 min

verstehe ich schon richtig, dass also mit den settings der shell 59 min offline sein darf

ich hab auch noch ein blockly laufen welches Alarm gibt wenn dieser länger als 15 min weg ist, das meldet aber nix offline.
diese blockly möcht ich eigentlich alle damit ersetzen

Version ist 2.9.1 installiert

**Comment by ciddi89** [comment]
Ja wenn du 60 min eingegeben hast dann sollte er sich erst melden wenn der Datenpunkt uptime 60min nicht aktualisiert wurde. Ich glaube bei Shelly war es auch so das dafür der Datenpunkt connected auf false sein muss. Bin mir da aber gerade ausn Kopf nicht mehr sicher. 
Werde es heute Abend mal testen und gucken ob da irgendwo im Code ein Fehler ist. Melde mich dann noch mal.

**Comment by freaktech** [comment]
danke bei den ikea rollos hab ich das gleiche auch also Trädfre

**Comment by ciddi89** [comment]
okay hatte nun mal Zeit nach zu gucken wie der Adapter bei Shelly den Status prüft. Hier nimmt er den Datenpunkt online, wenn dieser auf false geht sollte er die Zeit abwarten, die eingestellt wurde, dann wertet der device watcher diesen als offline. Merkwürdig nur das er bei dir den dann direkt wieder online meldet. Bei eingestellten 60min ist das sehr unwahrscheinlich. 

- Wurde der Adapter mal neu gestartet?
- Besitzt das Gerät die Datenpunkte online und uptime? 
- ist das nur bei ein Shelly Gerät der Fall oder bei mehreren?
- Evtl mal versuchen den Datenpunkt `online` zu beobachten wie der arbeitet.

Leider habe ich selber keine Shelly Geräte somit kann ich das nur mit selbsterstellen Datenpunkten so gut wie möglich versuchen zu simulieren und bin daher für jede Hilfe Dankbar um den Adapter und sein verhalten zu verbessern. :)

**Comment by freaktech** [comment]
ick komm hier nicht so wirklich weiter  es geht eigentlich shelly zigbee und tradre die diese Fehler immer wieder auswerfen

<img width="1230" alt="image" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/33237257/a7c9f0ea-e1b9-4e73-83bd-eb3ee3cbd100">


dies eMeldung hier sagt Ja das Gerät

"Dachboden ist seit 10:13   nicht mehr da, wieso kommt die Meldung um 10:17   das sind ja keine 60 Minuten wie oben eingestellt


<img width="543" alt="image" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/33237257/65a03dfb-3270-444a-8e2b-851342dbd076">

und ein paar Minuten später wieder da

<img width="543" alt="image" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/33237257/60f55f4c-34f6-44a3-aed8-623b7a3fcd97">

ich bezweifle dass es wirklich so ist, denn in der Praxis sind die shelly immer da, auch stimmen ja die 60 Min im Adapter nicht

danke
tom

**Comment by freaktech** [comment]
bei den Ikea rollos  zb

<img width="1191" alt="image" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/33237257/bb6c859e-57b3-46c8-b71f-4d15a1aaecea">

stimmt das ja eigentlich auch nicht

<img width="838" alt="image" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/33237257/5d57677a-b264-4c37-8e16-d9af1e066850">

**Comment by ciddi89** [comment]
Ikea kann/werde ich umstellen das er erst anfängt die Zeit abzuwarten wenn der alive datenpunkt auf false steht. Das sollte zumindest das Problem beheben.

Das andere muss ich mal ausführlich testen. Stehe da gerade selbst ein bisschen aufn Schlauch da mir sonst niemand diese Fehler gemeldet hat. Versuche aber herauszufinden woran das liegt.

**Comment by ciddi89** [comment]
Hast du ein Screenshot von den Datenpunkten zb. vom Gerät Dachboden?

**Comment by freaktech** [comment]
danke, bei den Shelly überwache ich auch den Punkt online    mit blockly  da kommen keine Fehler

**Comment by ciddi89** [comment]
Ach und noch eine Frage: DIe Instanz vom shelly startet aber nicht zwischendurch neu oder? Da die Zeiten von allen offline Geräten gleichzeitig ist. Muss irgendwie verstehen warum dies so ist und alle gleich zeitig gemeldet werden.

**Comment by freaktech** [comment]
na ja jetzt is ja wieder alles on aktuell   ausser eben die rollos weil sich da nichts tut

**Comment by freaktech** [comment]
sehe da eigentlich nichts was auf Neustart hinweist ?!?
<img width="1244" alt="image" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/33237257/91624879-18a1-417b-ac72-ad50a85021c6">

**Comment by ciddi89** [comment]
Ja einmal zum verständinis worauf ich hinaus will: Bei vielen Adaptern ist es so, wenn eine Instanz neu startet, dann werden alle Geräte für die Zeit als disconnected eingestuft. Habe dafür aber ein timer eingebaut der das abfangen soll. Naja wie auch immer besteht ja trotzdem bei dir das Problem das die Zeit von 60min nicht abgewartet wird. Falls das wieder vorkommt wäre es cool wenn du ein Screenshot von einem Gerät machen kannst wo man die Zeitstempel sieht. Wichtig für mich sind die Zeitstempel Zuletzt aktualisiert und Zuletzt geändert am besten mit der Info wann das Gerät gemeldet wurde vom device watcher. 
Hier ein Beispiel was ich meine:
<img width="1276" alt="Screenshot 2023-07-19 at 22 30 12" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/66088020/6652f1de-3f8f-4c75-bbb6-e61a3e11f52c">

**Comment by freaktech** [comment]
OK 
verstehe ich schau wenn wieder ein Telegramm morgen kommt   dass ich remote drauf komme und einen screenshot poste
