### ISSUE TITLE
Wert für schwachen Akku lässt sich nicht speichern.

### ISSUE THREAD

**Issue by Smo-RBR** [ciddi89/ioBroker.device-watcher#206]
Wenn ich den Wert ab wann ein Akku als schwach betrachtet wird, ändere, wird kein speichern angeboten. Auch wenn ich einen anderen Wert ändere um die Sve Button angezeigt zu bekommen, und dann speichere, bleibt der Wert für schwachen Akku auf 35%.

**Comment by ciddi89** [comment]
Hallo,

gibst du die Werte per Tastatur ein oder über die Pfieltasten die neben dem Zahleneingabe Feld sind? Leider ist das ein allgemeiner Fehler von Admin. Bei mir klappt es zb. manchmal nicht über die Pfeiltasten dann muss ich die Nummer Händisch per Tastatur eingeben.

**Comment by Smo-RBR** [comment]
Danke, mit der Tastatur hats geklappt.
