### ISSUE TITLE
was will mir der adapter damit sagen

### ISSUE THREAD

**Issue by arteck** [ciddi89/ioBroker.device-watcher#21]
![grafik](https://user-images.githubusercontent.com/6681528/181686917-66a5b591-7149-4997-a9ae-f3ca57fa4385.png)

**Comment by ciddi89** [comment]
Hier hat sich gestern der translator ausgetobt. Werde ich nachher noch mal überprüfen und und in ein verständlichen Text ändern.

**Comment by ciddi89** [comment]
Habe den Text geändert. Ich hoffe er ist nun besser zu verstehen. 

‘Hier können Sie die offline Zeiten von jedem Adapter definieren. Falls Sie direkt die Datenpunkte der Geräte (online, available, reachable usw.) nutzen wollen um den Status zu ermitteln, tragen sie '-1' ein.‘
