### ISSUE TITLE
Adapter sagt mit per Telegramm dass Telegram deaktiviert ist ;-)

### ISSUE THREAD

**Issue by freaktech** [ciddi89/ioBroker.device-watcher#216]
was sagt mir diese Meldung 2-3 mal am Tag?

ich hab da mal das Timeout jetzt von 60 auf 180 Sekunden gestellt 

aber das kann so doch nicht ganz korrekt sein

<img width="585" alt="image" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/33237257/c57575c7-f7d3-4a0b-a7a2-46fe6c9db707">

**Comment by ciddi89** [comment]
Telegram startet nachts, wenn man es nicht deaktiviert hat, einmal neu. Aber dieser Vorgang dauert keine 60 sek. Und selbst die voreingestellte Wartezeit von 20 sek sollte da nicht drauf anspringen. Auch komisch das es mehrmals am Tag auftaucht? Wäre cool wenn du den Datenpunkt 'system.adapter.telegram.0.alive' beobachten könntest ob der tatsächlich zwischen durch aussteigt. So wüsste ich sonst nicht was evtl. verkehrt sein sollte, da bei mir der Fehler nicht auftaucht und von anderen auch noch nicht gemeldet wurde. Tritt das nur bei telegram auf? Ist die Version vom device-watcher aktuell (v2.9.3)?
