### ISSUE TITLE
Instanz smartgarden wird als deaktiviert gemeldet

### ISSUE THREAD

**Issue by gonzokalle** [ciddi89/ioBroker.device-watcher#217]
Instanz Watchdog schreibt ein paar mal am Tag, dass smartgargen.0: Instanz deaktiviert ist.
Offlinezeit für smartgarden habe ich auf 10 Minuten eingestellt.
Den DP system.adapter.smartgarden.0.alive habe ich überwacht. Der ist durchgängig auf true.
Meine Version ist aktuell v2.9.3

**Comment by ciddi89** [comment]
Ist der Fehler noch Aktuell?

**Comment by gonzokalle** [comment]
Das kann ich nicht sagen. Habe den Smartgaden im Device-Watcher im Sommer deaktiviert, weil so viele Meldungen gekommen sind.

 

Von: Christian Behrends ***@***.***> 
Gesendet: Freitag, 3. November 2023 21:31
An: ciddi89/ioBroker.device-watcher ***@***.***>
Cc: gonzokalle ***@***.***>; Author ***@***.***>
Betreff: Re: [ciddi89/ioBroker.device-watcher] Instanz smartgarden wird als deaktiviert gemeldet (Issue #217)

 

Ist der Fehler noch Aktuell?

**Comment by ciddi89** [comment]
same as #262
