### ISSUE TITLE
Low Battery Issue with device HmIP-eTRV-2

### ISSUE THREAD

**Issue by basty2** [ciddi89/ioBroker.device-watcher#218]
**Describe the bug**  
in the low batterie list there are devices, which are not on low battery. It concerns all types of devices HmIP-eTRV-2

**To Reproduce**  
happens every time. a new start of iobroker and restarting the instance didn't help. 

**Expected behavior**  
the devices are not in the battery low list. 

**Screenshots & Logfiles**  

Low Bat list of Device Watcher
`[{"Device":"a","Adapter":"Homematic RPC","Battery":"2.8V"},{"Device":"b","Adapter":"Homematic RPC","Battery":"2.7V"},{"Device":"c","Adapter":"Homematic RPC","Battery":"2.8V"},{"Device":"d","Adapter":"Homematic RPC","Battery":"2.7V"},{"Device":"e","Adapter":"Homematic RPC","Battery":"2.6V"},{"Device":"f","Adapter":"Homematic RPC","Battery":"2.7V"},{"Device":"g","Adapter":"Homematic RPC","Battery":"2.7V"},{"Device":"h","Adapter":"Homematic RPC","Battery":"2.7V"},{"Device":"i","Adapter":"Homematic RPC","Battery":"2.7V"},{"Device":"k","Adapter":"Homematic RPC","Battery":"2.7V"},{"Device":"l,"Adapter":"Homematic RPC","Battery":"2.4V"}]`

Data for device e
![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/33844675/1d08c794-6c84-42cc-a056-63cafe06b160)

**Versions:**  
 - Adapter version: v2.9.3
 - JS-Controller version: <js-controller-version> 5.0.12
 - Node version: 18.17.1
 - Operating system: debian 12

**Comment by ciddi89** [comment]
Thank you for this report. Don't the devices have the data point 'lowbat alarm' ? I don't see it in your screenshot.

**Comment by basty2** [comment]
Hi. No, there is no datapoint lowbat alarm. Only lowbat. This is in my case 'false'.

**Comment by ciddi89** [comment]
Okay, then I have to add an fallback for this case. I‘ll work on it in the next days when I have time for it.

**Comment by basty2** [comment]
Hi @ciddi89, 

I just upgraded my version but the problem does still exists, doesn it?
