### ISSUE TITLE
checkbox is not available

### ISSUE THREAD

**Issue by arteck** [ciddi89/ioBroker.device-watcher#22]
https://user-images.githubusercontent.com/6681528/181687284-a275341c-70f0-436c-8486-f4dc86790d89.mp4

**Comment by ciddi89** [comment]
Welchen Browser nutzt du denn? Habe es bei mir gerade noch mal getestet mit Safari und Firefox, kann es aber nicht reproduzieren. Wäre dann evtl. ein allgemeiner Fehler der Admin UI. Bei der JSON Config zur Erstellung des Menüs habe ich kein großen Einfluss darauf.
