### ISSUE TITLE
save method is not available

### ISSUE THREAD

**Issue by arteck** [ciddi89/ioBroker.device-watcher#23]
https://user-images.githubusercontent.com/6681528/181687355-ce7a9f72-22a7-4b0b-873c-edcf7709998b.mp4

**Comment by ciddi89** [comment]
Wie im anderen Issue schon: welchen Browser nutzt du denn? Habe es bei mir gerade noch mal getestet mit Safari und Firefox, kann es aber nicht reproduzieren. Wäre dann evtl. ein allgemeiner Fehler der Admin UI. Bei der JSON Config zur Erstellung des Menüs habe ich kein großen Einfluss darauf.
