### ISSUE TITLE
Sonoff/Tasmota Geräte DeviceName bei Mitteilungen

### ISSUE THREAD

**Issue by micklafisch** [ciddi89/ioBroker.device-watcher#243]
**Is your feature request related to a problem? Please describe.**
Meine Tasmota Geräte haben alle die IP Adresse im Hostnamen um Variabel zu bleiben. Die logische Zuordnung der Steckdosen erfolgt über den Tasmota DeviceName, dieser wird aber nicht in der Benachrichtigung der Offline Geräte anzeigt

**Describe the solution you'd like**
Anzeige des "DeviceName" Feldes in der Telegram Mitteilung anstatt den Hostnamen des Geräts, siehe Screenshot.

**Additional context**
![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/44931749/764f6539-e4ec-4ea0-b372-fcc6af4413ee)

**Comment by ciddi89** [comment]
Habe ich mit aufgenommen. Wenn der Datenpunkt verfügbar sein sollte, wird der dort enthaltene Name genutzt. Wird in der nächsten Version mit drin sein. Wenn du es testen möchtest dann bitte die Github Version installieren.

**Comment by micklafisch** [comment]
wow, das ging flott, vielen Dank!

**Comment by micklafisch** [comment]
Hallo,
ich muss leider das alte Thema ausgraben. Es hat sich im aktuellen Tasmota die Struktur geändert, ich kann nur nicht ganz nachvollziehen seit wann. Der Hostname ist jetzt unter „Gerät“.INFO.Info2_Hostname zu finden.

Anbei ein aktueller Export, kannst du damit etwas anfangen?

Danke und Gruß

[sonoff.0.Gosund67.json](https://github.com/user-attachments/files/16825831/sonoff.0.Gosund67.json)
