### ISSUE TITLE
Klarmeldung kommt direkt mehrfach

### ISSUE THREAD

**Issue by micklafisch** [ciddi89/ioBroker.device-watcher#244]
**Describe the bug**  
Die Klarmeldung wenn ein Gerät wieder erreichbar ist, kommt per Telegram bei mir immer mehrfach

**To Reproduce**  
Gerät offline nehmen, warten und Gerät wieder online nehmen

**Expected behavior**  
Klarmeldung sollte pro Gerät nur 1x kommen

**Screenshots & Logfiles**  
![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/44931749/8c010a53-88b9-4e67-ad33-bd5d97a0162c)

**Versions:**  
 - Adapter version: 2.9.4
 - JS-Controller version: 4.0.24
 - Node version: v18.16.0
 - Operating system: docker

**Comment by ciddi89** [comment]
Hallo,
versuche derzeit das Problem nachzustellen aber irgendwie gelingt es mir nicht. Daher brauche ich bisschen mehr Information. 
- Betrifft das nur bestimmte Geräte oder ist es bei allen?
- Wurde ioBroker mal neu gestartet?
- Ist es möglich ein anderen Nachrichten Dienst zu testen? Wenn ja: Tritt dort der selbe Fehler auf? (Damit ich sicherstellen kann ob es ein Telegram Problem ist oder ein Allgemeines.)

Irgendwie ist mir aufgefallen das die Nachrichten immer nur in Verbindung mit Telegram spinnen. Vielleicht zufall aber ich werde versuchen herauszufinden was da los sein könnte.

**Comment by micklafisch** [comment]
Hi, 
mit etwas testen kann ich folgendes berichten:

es betrifft bei mir nur Geräte des Sonoff-Adapters (alles Gosund Steckdosen mit Tasmota). Egal ob Telegram oder Whatsapp - die Klarmeldung kommt bei denen immer 7x. Meine Shelly oder HM.rpc Geräte machen das nicht, die schicken 1x offline und 1x online.

Neustart vom ioBroker bringt nichts, hoffe die Infos helfen weiter.

**Comment by ciddi89** [comment]
Ja das hilft erstmal weiter. Das ist dann dann selbe/ähnliche Problem wie im issue #191 Werde mal paar tests machen und wenn ich was wissen muss melde ich mich noch mal. Ist halt schwierig zu reproduzieren wenn man die Geräte selbst nicht hat.

**Comment by ciddi89** [comment]
Beim Sonoff Adapter bin ich dran. Leider find ich nicht heraus woran das liegt. Evtl. kann mir einer Debug logs vom Sonoff Adapter und Device-Watcher schicken. In dem Moment wenn ein Gerät Online/Offline gemeldet wird. Bin da echt ratlos weil es eigentlich nicht funktionieren sollte bzw. ich bekomme es auch nicht hin nachzubilden. Mehr Infos würden mir da echt helfen.

**Comment by micklafisch** [comment]
Klar kann ich am Wochenende beide Adapter mal auf debug stellen und ein Gerät triggern. Log liefere ich dann umgehend

**Comment by micklafisch** [comment]
Log ist ungeschwärzt per Mail zu dir unterwegs

**Comment by ciddi89** [comment]
Ja ist angekommen. Schaue ich mir die Tage an. Auf jeden Fall schon mal vielen Dank dafür.

**Comment by ciddi89** [comment]
@micklafisch danke nochmal für dein Log. Ich hatte endlich mal Zeit mich da durch zu suchen und denke ich habe was gefunden. Der Sonoff Adapter meldet manchmal den Status alive = true innerhalb von wenigen ms mehrmals hintereinander. (Siehe Screenshot) Und da kommt mein Adapter aber nicht hinterher den State intern anzupassen, wodurch er denkt das das Gerät noch offline ist. Ich muss mir mal überlegen wie ich das am besten abfedern kann. Denke werde ein Delay mit rein nehmen der 1-2 Sekunden wartet. Vielleicht schaffe ich das heute noch. Muss ich mal sehen. Auf jeden fall wird da nun Zeitnah ein Fix für kommen. 💯 

<img width="1427" alt="Bildschirmfoto 2023-11-23 um 17 48 37" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/66088020/f15329da-1aaf-469e-8a24-24cb1fb9fb59">

**Comment by micklafisch** [comment]
Melde vollen Erfolg. Ausfall- sowie die Klarmeldung kommen bei meinen Sonoffs jetzt pro Gerät wie gewünscht genau 1x. 

Dankeschön für den Support!

**Comment by Ilovegym66** [comment]
Hier kommen die mehrfach Meldungen auch nicht mehr. Super!
Danke
