### ISSUE TITLE
HTML data points contain German strings on a system configured as English

### ISSUE THREAD

**Issue by agross** [ciddi89/ioBroker.device-watcher#245]
**Describe the bug**  
The HTML contains a mixture of German and English strings.

**To Reproduce**  
1. Configure ioBroker's system language as English
2. Install and configure adapter
3. Enable "Create additionally HTML lists"
4. Inspect e.g. `device-watcher.0.devices.lowBatteryListHTML`

**Expected behavior**  

* The header above the table should read "Low Battery Devices", not "Schwache Batterie Devices".
* The table header for the third column should read "Battery", not "Batterie".

**Screenshots & Logfiles**  
<img width="501" alt="2023-10-26_12-48-13" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/16245/fae37512-bddc-4200-8742-6451c5e52437">

<img width="391" alt="2023-10-26_12-48-58" src="https://github.com/ciddi89/ioBroker.device-watcher/assets/16245/ef46b7e0-9d63-4ab6-b823-0eeaaadfa5c8">

**Versions:**  
 - Adapter version: 2.9.4

**Comment by ciddi89** [comment]
I will add a translation for all tables and messages soon.
