### ISSUE TITLE
desired PID vs own PID 

### ISSUE THREAD

**Issue by softwarecrash** [ciddi89/ioBroker.device-watcher#246]
**Describe the bug**  
Hallo,
der Adapter läuft super (bis auf Mehrfachmeldungen vom sonoff adapter #244)

überwacht werden aktuell sonoff und zigbee geräte.
Die warnungen tauchen zusammenhanglos irgendwann auf und sind recht exakt dann im 15 min. abstand.
Es ist kein einzelproblem da auf einem zweiten system das gleiche verhalten auch auftritt.
Da es kein fehler ist ist, ist es nicht weiter schlimm, aber vielleicht lässt sich das beheben.

<html><body>

device-watcher.0 | 2023-10-29 11:45:04.270 | warn | Got terminate signal. Checking desired PID: 0 vs own PID 16244
-- | -- | -- | --
device-watcher.0 | 2023-10-29 11:30:04.227 | warn | Got terminate signal. Checking desired PID: 0 vs own PID 15469
device-watcher.0 | 2023-10-29 11:15:04.213 | warn | Got terminate signal. Checking desired PID: 0 vs own PID 14693
device-watcher.0 | 2023-10-29 11:00:04.237 | warn | Got terminate signal. Checking desired PID: 0 vs own PID 13910
device-watcher.0 | 2023-10-29 10:45:04.198 | warn | Got terminate signal. Checking desired PID: 0 vs own PID 13129
device-watcher.0 | 2023-10-29 10:30:04.213 | warn | Got terminate signal. Checking desired PID: 0 vs own PID 12351

</body>
</html>

**Versions:**  
 - Adapter version: 2.9.4
 - JS-Controller version: 5.0.12
 - Node version:  v18.17.1
 - Operating system: Linux / Docker

**Comment by ciddi89** [comment]
Beim Sonoff Adapter bin ich dran. Leider find ich nicht heraus woran das liegt. Evtl. kann mir einer Debug logs vom Sonoff Adapter und Device-Watcher schicken. In dem Moment wenn ein Gerät Online/Offline gemeldet wird. Bin da echt ratlos weil es eigentlich nicht funktionieren sollte bzw. ich bekomme es auch nicht hin nachzubilden. Mehr Infos würden mir da echt helfen.

Wegen der Warnmeldung:
Sonst keine Fehler meldung? Es ist exakt jede 15 min. Unter Instanz Einstellungen ist der aber nicht zufällig auf Cron gestellt oder? WIrklich seltsam. Evtl. auch hier auf debug stellen und schauen ob er dann dort mehr Infos gibt.

**Comment by softwarecrash** [comment]
es war tatsächlich ein cron hinterlegt bei der Instanz wobei ich mir sehr sicher bin den nicht manuell angelegt zu haben, hab ihn raus genommen. ich gehe mal davon aus das die Warnmeldung damit dann auch verschwindet.
wegen der mehrfachmeldung probier ich mal logs zu erstellen und in dem anderen issue zu posten wenn ich etwas abgreifen kann.
vielen dank.

**Comment by softwarecrash** [comment]
@ciddi89 Leider ist mit dem löschen den Cron ein anderes problem aufgetreten.
nach einem neustart des host systems steht die devicewatcher instanz jetzt mit einer einem uhr symbol da und im log taucht folgendes auf

<html><body>


host.iobroker | 2023-11-05 22:46:45.277 | error | system.adapter.device-watcher.0 schedule attribute missing
-- | -- | -- | --
host.iobroker | 2023-11-05 22:46:42.190 | info | stopInstance system.adapter.device-watcher.0 (force=false, process=false)


</body>
</html>

**Comment by softwarecrash** [comment]
Nach einem entfernen der instanz und neu installation ist jetzt alles wieder in ordnung, irgendwas aus alten zeiten hing da wohl noch fest
