### ISSUE TITLE
device-watcher has an invalid jsonConfig: 

### ISSUE THREAD

**Issue by Brainbug01** [ciddi89/ioBroker.device-watcher#248]
Admin v6.12.1 meldet beim öffnen des device-watcher Adapters:

```
device-watcher has an invalid jsonConfig: 
[{
"instancePath":"/items/_notifications/items/checkSendAdapterUpdateMsg/newLine",
"schemaPath":"#/patternProperties/%5E.%2B/properties/newLine/type",
"keyword":"type",
"params":{"type":"boolean"},
"message":"must be boolean"
},{
"instancePath":"/items/_notifications",
"schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if",
"keyword":"if",
"params":{"failingKeyword":"then"},
"message":"must match \"then\" schema"
}]
```

**Comment by mcm1957** [comment]
attribute newLine must have a boolean value but has string "true"

https://github.com/ciddi89/ioBroker.device-watcher/blob/84fcf09e4bebaf6b521c71a7ed00ea82084734a2/admin/jsonConfig.json#L418C6-L418C24

**Comment by Brainbug01** [comment]
Die Meldung hat sich geändert:

device-watcher has an invalid jsonConfig: 
[{
"instancePath":"/items/_notifications/items/_sendIntervallAdapterUpdateDay",
"schemaPath":"#/patternProperties/%5E.%2B/allOf/0/then/required",
"keyword":"required","params":{"missingProperty":"type"},
"message":"must have required property 'type'"
},{
"instancePath":"/items/_notifications",
"schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if",
"keyword":"if",
"params":{"failingKeyword":"then"},
"message":"must match \"then\" schema"
}]

Ich hoffe es ist richtig dass ich das nochmals zeige?

**Comment by ciddi89** [comment]
@Brainbug01 Ja, werde es fixen.
