### ISSUE TITLE
Wifilight

### ISSUE THREAD

**Issue by Ilovegym66** [ciddi89/ioBroker.device-watcher#264]
Hi,
can be Wifilight Adapter added, please? :)
The structure of the objects are like this:

wifilight.INSTANCE.IPADDRESS.reachable
wifilight.0.10_1_5_200.reachable

![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/36229898/f0b87186-baac-446d-992e-11a5e5642a5d)

thanks in advance!

**Comment by ciddi89** [comment]
Will be available in next release. :-)
