### ISSUE TITLE
Enocean

### ISSUE THREAD

**Issue by Trunks1982** [ciddi89/ioBroker.device-watcher#27]
Wäre es auch möglich enocean mit aufzunehmen damit er die Sensoren auch überwacht?

**Comment by ciddi89** [comment]
Bestimmt, brauche nur ein Überblick der Datenpunkte eines Enocean Gerät damit ich diese mit einpflegen kann. Ein Screenshot oder json Auszug aus der Objektauswahl könnte mir helfen. :)

**Comment by Trunks1982** [comment]
![Bildschirmfoto 2022-08-01 um 20 08 38](https://user-images.githubusercontent.com/62701386/182213667-afdf89e3-1444-40dc-ac05-b32c877bb14a.png)

Kein Problem sollst du gerne haben:-)

**Comment by ciddi89** [comment]
Ok hab es mit neuen commit https://github.com/ciddi89/ioBroker.device-watcher/commit/cbb79a521d150651fe9e0fd1abf8fc551659df08 hinzugefügt. einfach neu drüber installieren und bitte testen ob er die Geräte findet.

**Comment by Trunks1982** [comment]
Perfekt hat die Geräte gefunden.Danke
