### ISSUE TITLE
You might be interested in (Lovelace embedding)

### ISSUE THREAD

**Issue by o0shojo0o** [ciddi89/ioBroker.device-watcher#28]
I have created a small script which creates HTML data points from your adapters for me to embed them in Lovelace. 
https://github.com/o0shojo0o/iob.Device-Watcher_ToHTML

**Comment by ciddi89** [comment]
Thank you for your script! It looks very good and it's really useful for other people. I will test it later and will add an information about it in the readme. Maybe in the future it is possible to add the script nativ to the Adapter if you are okay about that. I think it's useful for other visualization too. 🙂

**Comment by o0shojo0o** [comment]
Of course, I would be happy to contribute the script to the adapter.

**Comment by o0shojo0o** [comment]
If you want I can also submit a pull request if you give your ok to the to the script.

**Comment by ciddi89** [comment]
> If you want I can also submit a pull request if you give your ok to the script. 

Yes, sure. If you want it's no problem.
