### ISSUE TITLE
Fully Tablet wird offline und online dargestellt 

### ISSUE THREAD

**Issue by Brainbug01** [ciddi89/ioBroker.device-watcher#281]
Alle Adapter aktuell im Beta.

Details siehe:
https://forum.iobroker.net/topic/55426/test-adapter-device-watcher-v2-x-x-github-latest/1397?_=1701975194206

**Comment by ciddi89** [comment]
Da ich so gut wie garnicht mehr im Forum bin habe ich das wohl offensichtlich nicht gesehen. Sorry dafür.

Werde es die Tage testen und wenn noch fragen sind melde ich mich nochmal. :)

**Comment by Brainbug01** [comment]
Und als Erinnerung: Denk auch an den Namen des Tablets, das es nicht der hostname4 sein soll.

**Comment by Brainbug01** [comment]
> wie genau meinst du das? Du beendest die App, der Device Watcher meldet das es offline ist aber wird in den Listen als online angezeigt? Hilf mir mal bitte auf die Sprünge. :)

Ja wie auf dem Bild im Forum zu sehen ist beende ich die Fully App. Und dann wird es in beiden Listen angezeigt. Sollte dann ja nur in der offline Liste sein. 

> Zusätzlich schreibt du das das WifiSignal kein gängiger werd ist. Also wahrscheinlich zu niedrig sei? Hast du Beispiel Werte damit ich durchrechnen kann ob die wirklich falsch berechnet sind?

3% 4% oder 0% wifi signal steht für was? Es gibt in den Objekten das Info.wifiSignalLevel wie du das umrechnest weiß ich nicht. 

> Batteriewerten

Hab ich mir gedacht dass die Logik umgebaut werden muss, musst du entscheiden. Eine Warnung ist sicher hilfreich weil die Stromladung auch mal ausfallen könnte. Mögliche Hardware schaltet den Strom nicht ein...

**Comment by ciddi89** [comment]
Ah okay, ja aber es gibt gar keine reine "online" Liste. Die Liste die du zeigst ist die "allDevices" liste oder nicht? Da fehlst aber noch eine Spalte mit Status wo drin steht online oder offline wenn ich es richtig sehe. 


Zum Wifi: Naja guck dir deine Datenpunkte direkt an von den Geräten was in den rssi states steht.   Normalerweise ein negativer Wert. Den meinte ich. Dieser wird Adapterseitig umgerechnet in ein Prozentwert. Es gibt aber im device watcher im letzten Menü Tab eine checkbox womit man sich stattdessen den original Wert in den Listen anzeigen lassen kann.

**Comment by Brainbug01** [comment]
> Ah okay, ja aber es gibt gar keine reine "online" Liste. Die Liste die du zeigst ist die "allDevices" liste oder nicht? Da fehlst aber noch eine Spalte mit Status wo drin steht online oder offline wenn ich es richtig sehe.

Stimmt, sorry das ist wirklich verwirrend. Oben ist die online Liste und unten das eine Tablet ist die offline Liste. 

> Zum Wifi:

Es gibt beim fully kein rssi Wert in den Objekten. Welchen Datenpunkt verwendest du um das anzuzeigen?

**Comment by ciddi89** [comment]
ja genau den Datenpunkt wifiSignalLevel nutze ich. Soweit ich weiss was es sonst ein RSSI Wert. Habe es nun aber abgeändert, in Zukunft wird bei fullyBrowserV3 einfach der gegebene Wert genommen.

Wie gesagt, es gibt keine reine Liste mit Geräten die Online sind. Nur eine Liste mit allen Geräten.

**Comment by Brainbug01** [comment]
> ja genau den Datenpunkt  nutze ich. 

Gäbe es da keine ungefährer Umrechnungsfaktor:

wifiSignalLevel 1 = rssi -10
wifiSignalLevel 2 = rssi -20
wifiSignalLevel 3 = rssi -30

Ist nur ein Beispiel. Da bei wifiSignalLevel 9 kein rssi -90 raus kommen kann. Ich denk aber du verstehst was ich meine?

> Wie gesagt, es gibt keine reine Liste mit Geräten die Online sind. Nur eine Liste mit allen Geräten.

Ach dann hab ich zuviel gedacht... Dachte wirklich es gibt ne online und offline Liste und beide sind getrennt von einander.

**Comment by ciddi89** [comment]
> Gäbe es da keine ungefährer Umrechnungsfaktor

Ich weiss nicht warum oder woher der Entwickler diese Zahlen nimmt. Vielleicht guck ich bei Gelegenheit mal in den Code ob da was zu finden ist. 

Ticket wird geschlossen wenn ich die Änderung hochgeladen habe, also alles gut :)

**Comment by ciddi89** [comment]
Release v2.9.10 mit fix ist raus gegangen. Sollte dann Zeitnah in beta repo verfügbar sein.

**Comment by Ilovegym66** [comment]
Hi, Danke fuer 2.9.10 !! das mit dem On/Offline funktioniert in der Version 2.9.10, und den Namen hast du auch geaendert, allerdings wird jetzt die IP Adresse (ist bei den iobroker-states bei Name) angezeigt, was schoener waere, wenn der Name des Tablets angezeigt werden wuerde (ist bei iobroker-states die ID, siehe Foto).. 

![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/36229898/76fb3796-f498-489c-afb6-3559d43cfd93)

**Comment by Brainbug01** [comment]
Und bzgl. dem Wifi Signal ist hier was:

This is the result of this Android API [calls]

WifiManager.calculateSignalLevel(wifiInfo.getRssi(), 10);

developer.android.com/reference/android/net/wifi/WifiManager#calculateSignalLevel(int, int)

**Comment by ciddi89** [comment]
@Ilovegym66 aah okay, war auf dem screenshot nicht ersichtlich. Habs verbessert und wird in v2.9.11 endgütig gefixed sein. 

@Brainbug01 Ja okay hab mir mal die docs durchgelesen von Developer Android. Hier wird der RSSI wert in 10 Qualitätsstufen unterteilt. 0 ist niedrig und 10 ist Hohe Signal Stärke. Warum der Entwickler nicht einfach den blanken RSSI Wert nimmt, Idk. Ist dann aber auch nicht mehr meine Baustelle. :)

**Comment by Ilovegym66** [comment]
Super, vielen Dank, jetzt ist das PERFEKT !! 
![image](https://github.com/ciddi89/ioBroker.device-watcher/assets/36229898/fafc709e-3f0b-4cd5-9ac7-a7dd019436f9)
