### ISSUE TITLE
Shelly Devices w/o Battery

### ISSUE THREAD

**Issue by Joylancer** [ciddi89/ioBroker.device-watcher#282]
**Describe the bug**  

Shelly Button, Shelly DW2, Shelly Flood shows no RSSI
shelly.0.SHBTN-1#98CDAC1E7151#1.rssi (fail)
shelly.0.SHBTN-1#98CDAC1E7151#1.bat.value (works)

Shelly Plus2PM, Shelly PlusHT shows no Battery and no RSSI
shelly.0.shellyplusht#2#1.DevicePower0.BatteryPercent (fail)
shelly.0.shellyplusht#1#1.rssi (fail)
![grafik](https://github.com/ciddi89/ioBroker.device-watcher/assets/99641044/5fa51c4e-f264-406c-b835-25fa3f27bb86)

**Versions:**  
 - Adapter version: device-watcher 2.9.9
 - JS-Controller version: 5.0.17
 - Node version: 18.19.0
 - Operating system: debian bookworm on HP Elitedesk

**Additional context**

**Comment by ciddi89** [comment]
Die Geräte haben alle den Status `Offline`  dann wird der Wert vom RSSI automatisch auf 0 gesetzt. 
Sind diese tatsächlich offline oder wird das falsch aufgenommen? Haben die den Datenpunkt `reach`? Wenn ja was zeigt dieser an? Wenn nein, gibt es einen vergleichbaren Datenpunkt?

**Comment by Joylancer** [comment]
Die anderen Geräte zeigen auch alle "Offline" an, sind ja Batterie betrieben, aber den RSSI Wert und den Akkuzustand wird im Shelly Adapter angezeigt.
Die Geräte gehen immer bei Änderungen online. Vielleicht kann man so den letzten Wert anzeigen. On-Offline sollte so bleiben.
Habe gerade mit dem Flood getestet, sobald Alarm ausgelöst wird, zeigt er auch einen RSSI Wert an.
Nur die Thermometer nicht -shellyplusht-. Ich experimetiere gerade mit den On-Offline Zeit-Werten in den Settings. 

Zwei andere Sachen sind mir noch aufgefallen.
1. Ich habe die JSON Tabellen in Jarvis mit dem entsprechenden Widget eingebunden. Aktualisierung im Adaper 60 sec.
Bei Aktualisierung wirft er alle Tabellen kurz durcheinander und sortiert diese dann neu..
![grafik](https://github.com/ciddi89/ioBroker.device-watcher/assets/99641044/0f8649ad-50e4-4564-aaf0-14db303f7a19)

2. Bei Zigbee Routern zeigt er kein RSSI Wert an, Die Datenpunkte sind aber die selben.
Sonoff zbmini, Presencesensor, 2x Sonoff Pro Sticks
Falls da noch etwas brauchst, kann ich dir schicken.
Vielen Dank aber auch für deine Arbeit hier.

**Comment by Joylancer** [comment]
Ich habe mal die Zeiten für Offline bei Shelly auf 3 Stunden gesetzt.
Online Geräte zeigen keinen Batterie Status an,

**Comment by Joylancer** [comment]
Hier ein Bild bei der Aktualisierung. Die gleichen Geräte sind dann auch unter Shelly zu sehen.
Nach ein paar Sekunden verschwindet wieder alles und die Listen stimmen wieder.
![grafik](https://github.com/ciddi89/ioBroker.device-watcher/assets/99641044/58f4b099-be00-4c69-b6a2-d3c13e655c82)

**Comment by Joylancer** [comment]
can you add  "shelly.0.*.DevicePower0.BatteryPercent" as BatteryPercent
Batterystate Shelly Plus HT

**Comment by Joylancer** [comment]
![grafik](https://github.com/ciddi89/ioBroker.device-watcher/assets/99641044/0d252d55-886a-48a9-b209-74b34553216b)

**Comment by ciddi89** [comment]
Okay so it looks that Shelly has a third type of Batterie datapoints for some devices. I'll add this in the next days.

**Comment by ciddi89** [comment]
Mit der nächsten Version wird der neue Datenpunkt für die Batterie mit berücksichtigt. 

Bzgl. den Wunsch den Wert der Verbindungsqualität anzuzeigen auch wenn das Gerät offline ist, habe ich einen neuen Menüpunkt unter andere Einstellungen hinzugefügt wo man dies aktivieren kann.

**Comment by Joylancer** [comment]
> Mit der nächsten Version wird der neue Datenpunkt für die Batterie mit berücksichtigt.
> 
> Bzgl. den Wunsch den Wert der Verbindungsqualität anzuzeigen auch wenn das Gerät offline ist, habe ich einen neuen Menüpunkt unter andere Einstellungen hinzugefügt wo man dies aktivieren kann.

Super, Danke

**Comment by Joylancer** [comment]
Update über GIT, läuft, Top.
Danke und noch schönes WE.
