### ISSUE TITLE
Instanz Watchdog funktioniert nicht richtig

### ISSUE THREAD

**Issue by AlexanderSch90** [ciddi89/ioBroker.device-watcher#292]
**Describe the bug**  
Der Instanz Watchdog gibt den Fehler "Instanz Watchdog:zigbee2mqtt.0: Nicht verbunden mit Gerät oder Dienst" aus, wenn der Adapter zigbee2mqtt neugestartet wird, obwohl in den Experteneinstellungen die Fehlzeiten auf 200 Sekunden erhöht wurden. Zudem wurden die "Offlinezeiten" in den Experteneinstellungen alle auf 10 Minuten erhöht. 

**To Reproduce**  
In Optionen einen Adapter überwachen (z.B. zigbee2mqtt)
In den Experteneinstellungen die Fehlzeiten auf 200 Sekunden erhöhen und die "Offlinezeiten" auf 10 Minuten setzen.
Danach den Adapter zigbee2mqtt neustarten.
Es kommt eine Benachrichtigung: "Instanz Watchdog:zigbee2mqtt.0: Nicht verbunden mit Gerät oder Dienst".
Es kommt keine Benachrichtigung, dass der Adapter wieder läuft. 

**Expected behavior**  
Es soll keine Benachrichtigung kommen, solange der Adapter nicht 200 Sekunden Aktiv ist. 

**Versions:**  
 - Adapter version: v2.9.13
 - JS-Controller version: 5.0.17
 - Node version: v18.19.0
 - Operating system: docker linux

**Comment by SurfGargano** [comment]
Ist bei mir auch. Ich habe global 3600 s Deaktivierungszeit und Fehlerzeit Timeout eingestellt. Wenn ich den z.B. Tibberlink Adapter neu starte, kommt sofort die Meldung. Sollte eigentlich gar keine Meldung kommen, da die Deaktivierungszeit nur einige Sekunden beträgt.
Adapterversion 2.9.14

Ich habe DeviceWatcher wieder deaktiviert, so kann ich es nicht gebrauchen. Sorry.

**Comment by ciddi89** [comment]
Also verstehe ich euch richtig das diese Meldungen nur beim neu starten eines Adapters kommen?

**Comment by SurfGargano** [comment]
Bei mir ja. Andere Situationen in denen der Adapter stopped kann ich jetzt nicht herstellen.

**Comment by ciddi89** [comment]
Hm okay werde mal gucken aber scheint wohl ein sehr spezieller seltener Fall zu sein daher ist es immer noch nicht so einfach für mich den Grund herauszufinden. Aber ich bleibe dran.


Danke für die Rückmeldung was den load angeht. Das war vorher auch so. Nur habe die Filterungen nun geändert und die Loops dafür rausgeschmissen. Zusätzlich war ein Fehler in der Funktion wenn ein Objekt geändert wurde. Da wurde jedes Mal die Hauptfunktionen aufgerufen bei der beachtlichen Menge die die User an Objekten haben war das natürlich ein Speicher fresser. Daher wunderte mich das da vorher schon keine Beschwerden kamen. 😂 naja die großen heiligen devs sind ja der Meinung das das abonnieren aller states besser wäre und diese zu filtern. Aber das hat in den letzten zwei Versionen zu erheblichen Problemen geführt. Daher bleibe ich jetzt erstmal bei der alten Methode. Vielleicht hatte ich das auch falsch angestellt. Who knows... fass das erstmal nicht mehr an 😂

**Comment by SurfGargano** [comment]
Wenn ich beim Debuggen helfen kann, sag Bescheid. Die Behebung der Situation, daß alle 45 s eine Meldung kommt, ist mir am wichtigsten.

**Comment by ciddi89** [comment]
Should be fix with v.2.10.5. Have to wait some more days then I will release it as stable version.
