### ISSUE TITLE
iobroker device-watcher with shelly plus Gen2

### ISSUE THREAD

**Issue by wobi-hacs** [ciddi89/ioBroker.device-watcher#293]
I am using iobroker with device-watcher 2.9.13.
It works for all battery devices from z-wave, sonoff and shelly Gen1 but not for shelly plus Gen2 devices like the shelly smoke plus device.
My feeling is that because the battery states in Gen2 devices are now reported under objects "DevicePower0" and not under "sensors" like Gen1 devices the adapter is not able to get this states.
Could that be the case?
Is this already a known issue and someone is working on that?

Best regards
Wolfgang

**Comment by ciddi89** [comment]
Hi Wolfgang,

yes the issue is already known #282  and will be fixed in next version.
