### ISSUE TITLE
Fritzdext Geräte offline mit 2.10.0

### ISSUE THREAD

**Issue by Brainbug01** [ciddi89/ioBroker.device-watcher#295]
Heute 2.10.0 installiert und nach einer unbestimmten Zeit werden alle DECT Geräte als offline gemeldet. Steuern über die Objekte funktioniert ohne Probleme. 2.9.14 macht keine Probleme. 

Present steht überall auf true, mal ein Beispiel:
![Screenshot_2024-01-13-11-04-10-427_com android browser-edit](https://github.com/ciddi89/ioBroker.device-watcher/assets/35106961/11fdff52-e5d1-4c57-b228-58a6e4ec8855)

**Comment by ciddi89** [comment]
Bitte mal GitHub version installieren

**Comment by Brainbug01** [comment]
Installiert, ich melde mich wieder.

**Comment by Brainbug01** [comment]
Funktioniert.
