### ISSUE TITLE
[writeDatapoints] - TypeError: .for is not iterable

### ISSUE THREAD

**Issue by fzoellne** [ciddi89/ioBroker.device-watcher#297]
**Describe the bug**  
After upgrade to version 2.10 I get the following error message:
`	2024-01-14 14:14:03.660	error	[writeDatapoints] - TypeError: .for is not iterable`

**To Reproduce**  
1. Update to version 2.10 of the adapter
2. Start instance
3. Check logs

**Expected behavior**  
nor such error message

**Screenshots & Logfiles**  
`	2024-01-14 14:14:03.660	error	[writeDatapoints] - TypeError: .for is not iterable`

**Versions:**  
 - Adapter version: 2.10
 - JS-Controller version: 5.0.17
 - Node version: v18.19.0
 - Operating system: Debian GNU/Linux 11 (bullseye)

**Additional context**  
Biobroker runs on a raspberry pi 4

**Comment by ciddi89** [comment]
If you install over GitHub, it is already fixed. 

When I have fixed another problem, then I will release a new version.

**Comment by fzoellne** [comment]
cool thx
