### ISSUE TITLE
Blacklist für HTML-Liste funktioniert nicht

### ISSUE THREAD

**Issue by gui2180** [ciddi89/ioBroker.device-watcher#299]
**Describe the bug**  
Nach upgrade von 2.9.14 auf 2.10.2 funktioniert die Blacklist für die HTML-Liste nicht mehr. Zwei Zigbee Geräte werden in der HTML Liste angezeigt, obwohl sie in der Blacklist stehen. 
In der JSON Liste ist kein Eintrag, der Counter steht auf 0. Nur in der HTML Liste tauchen die Geräte trotz Eintrag in der Blacklist auf.

**To Reproduce**  
Mit 2.9.14 kein Eintrag in HTML Liste, nach update auf 2.10.x als fehlend in der HTML Liste

**Versions:**  
JS-Controller version: 5.0.17
Plattform: linux
Node.js: v20.11.0
NPM: 10.2.4

**Comment by Ilovegym66** [comment]
kann ich hier nachvollziehen, war auch in der 2.10.1, musste auf die 2.9.14 zurück gehen. Fehler tauchen keine im Logfile auf.

**Comment by ciddi89** [comment]
Ja hab intern die falschen Listen genutzt dafür. Wird mit der nächsten Version wieder funktionieren.
