### ISSUE TITLE
Homeatic Last Contact Fehlerhaft

### ISSUE THREAD

**Issue by lindi200000** [ciddi89/ioBroker.device-watcher#30]
Hallo,
ich habe hier ein HM-Sec-SCo Fenster Kontakt.
Der funktioniert auch wunderbar, nur der Adapter sagt mir, das der letzte Kontakt über 300 Tage her ist.

`{"Device":"Fenster Büro:0","Adapter":"Homematic","Battery":" - ","Signal strength":"0%","Last contact":"338 Tagen","Status":"Online"}`

Der State Datenpunkt hatte die letzte Änderung vor 2 Tagen.

Was ließt der Adapter hier genau aus? Der Rest wie Battery und Signalstärke stimmt. Das wird nicht geliefert in Homematic.

Adapter Version ist 0.2.4

Sollten noch Daten gebraucht werden, dann einfach melden.

VG

**Comment by ciddi89** [comment]
Hallo @lindi200000,

Hier wird der unreach State genommen, wann dieser Datenpunkt zuletzt aktualisiert wird. In der Regel melden die sich alle paar Stunden. Leider gibt es aber bei paar Geräte Ausnahmen wie ich immer wieder sehe, ist leider nicht nur bei Homematic so. Hatte aber selbst noch nicht solche Auffälligkeiten. Evtl muss ich mir dafür einen anderen Datenpunkt aussuchen der regelmäßiger aktualisiert wird. Werde es mal bei meinen Geräten beobachten. Vielleicht kannst du ja bei deinem Gerät auch gucken welcher Datenpunkt aktueller ist. See Zeitstempel für aktualisiert ist wichtig, nicht der für letzten stage change. Ich danke schon mal.

**Comment by lindi200000** [comment]
in dem Fall ist es wirklich der State, der hat einen Zeitstempel von vor 15 Minuten.
`hm-rpc.0.OEQxxxxxx885.1.STATE`

**Comment by ciddi89** [comment]
Hmm okay, werde es mir die Tage angucken und bei meinen Geräten beobachten und wenn es passt werde ich es evtl auf den State umändern. Muss aber dafür sicher gehen das diese sich auch oft genug melden und nicht nur wenn diese ausgelöst werden.

**Comment by ciddi89** [comment]
Hallo @lindi200000 

habe nun bisschen ausprobiert und geguckt. Das ich den State Datenpunkt dafür nehme kann ich wohl erstmal vergessen. Dafür gibt es einfach zu viele verschiedene Ordnerstrukturen bei den Homematic geräten und teilweise auch mehrere State Datenpunkte so das diese öfters aufgelistet werden. Das bekomme ich dann nicht herausgefiltert. Ist das ein HM oder ein HMiP gerät? die haben manchmal unterschiedliche Datenpunkte. Kannst du mir ein Screenshot davon schicken vielleicht? Ich danke dir schon mal.

**Comment by lindi200000** [comment]
@ciddi89 
das ist ein normaler HM Fenster Contact.
![image](https://user-images.githubusercontent.com/16406425/184547394-6facf2e8-5521-4d75-b49a-e0529dadd870.png)
Hier der Objektbaum dazu.

**Comment by ciddi89** [comment]
Hmm Okay danke. Ich kann mir vorstellen das der hm Fenster Kontakt einfach diese Sachen noch nicht liefert, daher werden die Datenpunkte auch nicht aktualisiert. Außer wahrscheinlich low bat und state. Muss ich mal schauen ob ich dafür eine Lösung finde.

**Comment by ciddi89** [comment]
Hallo @lindi200000 hatte ein bisschen länger gedauert aber hatte heute vormittag mal Zeit bisschen was auszuprobieren. Habe nun erstmal grob zum testen eine Abfrage mit reingenommen falls die erforderlichen RSSI Werte nicht geliefert werden, das er dann vom den State Wert die Zeitstempel nimmt. Könntest du, wenn du Zeit hast, dies mal Testen ob es nun so bei dir funktioniert? Wenn ja kann ich das später hübscher codieren und weiter ausarbeiten. Ich danke dir schon mal. :)
