### ISSUE TITLE
Namenkonventionen

### ISSUE THREAD

**Issue by arteck** [ciddi89/ioBroker.device-watcher#309]
könntest du im Adapter ein eliste mit Namenskonventionen machen

const Adapter_text = 'Adapter';
const Instanz_text = 'Instance';
const Device_text = 'Device';
const Status_text = 'Status';
const isBatteryDevice_text = 'isBatteryDevice';
const BatteryRaw_text = 'BatteryRaw';
const Battery_litt_text ='Battery';
const BatteryRaw_unit_text = 'BatteryUnitRaw';
const isLowBat_text = 'isLowBat';
const Signal_strength_text = 'Signal strength Raw';
const Last_contact_text = 'Last contact';   

das sind alle Tags die im JSON vorkommen.. so dass man sich die selbst Übersetzten kann und diese dann in die Listen rein kommen

zur Zeit ist da ein mischmasch aus Englisch und Deutsch.. und es nervt total mir meine Scripte umstellen zu müssen

![grafik](https://github.com/ciddi89/ioBroker.device-watcher/assets/6681528/899565c0-8014-43cb-bb26-da444fda353a)

**Comment by ciddi89** [comment]
Seit 2.10.0 werden alle Texte in der eingestellten Systemsprache übersetzt :) Die Version ist nur noch nicht in stable

**Comment by arteck** [comment]
warum gehst du von aus dass ich Deutsche namen haben will ?

**Comment by ciddi89** [comment]
Ist nicht nur Deutsch und Englisch. Alle anderen Sprachen die es bei iobroker zur Verfügung stehen sind auch dabei. Kann aber einen Menü Punkt hinzufügen wo man die Sprache auswählen kann, falls man nicht die Systemsprache haben möchte.

**Comment by arteck** [comment]
gute idee

**Comment by ciddi89** [comment]
Habe in den Einstellungen unter "Andere Einstellungen" / "Other Options" einen Menüpunkt hinzugefügt wo man gewünschte Sprache für Tabellen und Nachrichten auswählen kann. Auswahl ist Optional, Standart Wert ist Systemsprache. Wenn gewünschte Sprache Fehler in den Texten enthalten dann bitte ein PR mit berichtigung in der JS Datei https://github.com/ciddi89/ioBroker.device-watcher/blob/main/lib/translations.js

**Comment by arteck** [comment]
![grafik](https://github.com/ciddi89/ioBroker.device-watcher/assets/6681528/9e0ec886-e3f1-45b6-9413-f7a1e18475a8)

gesehen.einen hast du vergessen

**Comment by ciddi89** [comment]
nö nicht vergessen, wurde auch ursprünglich mit übersetzt. Da stresste dann aber die Community weil es im Forum einige Skripte gibt die auf diese raw liste bassieren. Daher bleibt die raw liste auch raw. Übersetzung mit inbegriffen.
