### ISSUE TITLE
Messages are not emptied but added

### ISSUE THREAD

**Issue by mctom** [ciddi89/ioBroker.device-watcher#312]
**Describe the bug**  
Messages are not emptied but added. The list is emptied after a restart.

**To Reproduce**  
Set up automatic daily sending of a telegram message.

**Expected behavior**  
Just a list of current devices / adapters.

**Screenshots & Logfiles**  
Example last Message for Adapters:
Tägliche Übersicht über verfügbare Adapter Updates: 
Admin: v6.13.21
Backitup: v2.10.11
Fullybrowser: v3.0.10
Js-controller: v5.0.19
Telegram: v3.1.0
Vis-2: v2.9.32
Vis-2-widgets-energy: v0.3.11
Web: v6.2.4
Admin: v6.13.21
Backitup: v2.10.11
Fullybrowser: v3.0.10
Js-controller: v5.0.19
Telegram: v3.1.0
Vis-2: v2.9.32
Vis-2-widgets-energy: v0.3.11
Web: v6.2.4
Admin: v6.14.0
Backitup: v2.10.11
Fullybrowser: v3.0.10
Js-controller: v5.0.19
Telegram: v3.1.0
Vis-2: v2.9.32
Vis-2-widgets-energy: v0.3.11
Vis-2-widgets-jaeger-design: v1.1.12
Vis-2-widgets-material: v1.3.20
Web: v6.2.4

**Versions:**  
 - Adapter version: 2.10.3
 - JS-Controller version: 5.0.17
 - Node version: 18.19
 - Operating system: Linux

**Additional context**

**Comment by ciddi89** [comment]
Hallo @mctom, 

gilt das nur für die Nachricht der Adapter Updates oder tritt dieser Fehler auch bei anderen Nachrichten auf?

**Comment by mctom** [comment]
Er tritt bei allen Nachricht auf. Und auch in den Objekten sie die Daten mehrfach.

**Comment by ciddi89** [comment]
Oh okay. Merkwürdig das sich da noch keiner gemeldet hat. Fing das aber einer bestimmten Version an? Wurde das System mal neu gestartet?

**Comment by mctom** [comment]
Habe das System noch einmal komplett neu gestartet und beobachtet. 
Der Fehler tritt weiterhin auf. Wenn ich den Adapter neu starte ist beim ersten Versand alles okay. Mit dem 2. Versand werden die neuen Infos immer ergänzt.
Ich meine der Fehler ist nach dem letzten Update aufgetreten.

**Comment by ciddi89** [comment]
Okay denke habe den Fehler gefunden für die Übersicht Nachrichten. Werde vielleicht später noch eine neue Version raushauen, dann werden wir die Tage sehen ob das gefixed ist.

**Comment by mctom** [comment]
Fehler ist bei mir gefixed und tritt nicht mehr auf.
Danke für den Support.
