### ISSUE TITLE
Please add the jeelink adapter.

### ISSUE THREAD

**Issue by o0shojo0o** [ciddi89/ioBroker.device-watcher#32]
**Is your feature request related to a problem? Please describe.**
Please add the jeelink adapter. 

**Describe the solution you'd like**
All data points are re-set approximately every 10 seconds, yes really that often! 

**Additional context**
```json
{
  "type": "state",
  "common": {
    "name": "Battery Low",
    "type": "boolean",
    "role": "indicator.lowbat"
  },
  "native": {},
  "from": "system.adapter.jeelink.0",
  "user": "system.user.admin",
  "ts": 1638137687685,
  "_id": "jeelink.0.LaCrosse_TR_Sensor_TempHum.lowBatt",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```
![image](https://user-images.githubusercontent.com/19333515/183995947-e74f946a-f71a-4bd9-83c1-399c1ec4437d.png)

**Comment by ciddi89** [comment]
Done! Please give me a feedback if its working correctly.

**Comment by o0shojo0o** [comment]
Unfortunately does not show up under `device-watcher.0.listAll`.

**Comment by o0shojo0o** [comment]
Stop everything back, had forgotten to enable it in the config....
