### ISSUE TITLE
Ring Kamera Support 

### ISSUE THREAD

**Issue by DickenSerm** [ciddi89/ioBroker.device-watcher#323]
**Which adapter should be implement:**
[ioBroker.ring](https://github.com/iobroker-community-adapters/ioBroker.ring)

**The following information is important to add the adapter correctly, if possible add a json or screenshot with the information:**
Es steht alles in dem JSON File im Anhang, aber hier die Liste der Datenpunkte von mir, die interessant sein könnten (Ich hab zwei Kameras, aber die Datenpunkte sind identisch, daher hier nur von einer meiner Kameras):
| Datenpunkt  | Name | Wert (Beispiel)
| ------------- | ------------- | ------------- |
| ring.0.stickup_130873015.Info.battery_percentage | Battery | 100% |
| ring.0.stickup_130873015.Info.battery_percentage_category | Battery Category | very_good |
| ring.0.stickup_130873015.Info.hasBattery | Has Battery | true |
| ring.0.stickup_130873015.Info.latest_signal_category | WLAN Signal Category | good |
| ring.0.stickup_130873015.Info.latest_signal_strength | WLAN Signal | -57 RSSI | 
| ring.0.stickup_130873015.Info.external_connection | External Power | false |
| ring.0.stickup_130873015.Info.firmware | Firmware | Up to Date | 

**Additional context**
Ich hab mal die komplette JSON vom Ring Adapter angehangen
[ring.json](https://github.com/ciddi89/ioBroker.device-watcher/files/14613980/ring.json)

**Comment by ciddi89** [comment]
Super, danke für die ganzen Infos! Das ist perfekt so. Werde ich dann am WE mit einpflegen.
