### ISSUE TITLE
Umbenennung der JSON-Listen auf lokale Sprache

### ISSUE THREAD

**Issue by mango1402** [ciddi89/ioBroker.device-watcher#325]
Hallo.
dies ist kein richtiger Defect, eher ein unschöner Effekt....

Sprache einstellen? Ja, super! Aber nur für die GUI.
Aber man kann doch nicht die 'Benennungen' für Datensätze (also konkret in den JSON-Listen) ändern! z.B. Device -> Gerät
Damit muss man sämtliche Funktionen, die auf diese Listen zugreifen umändern und - wie aktuell - auch noch nationale Sonderzeichen (Umlaute) verwenden! Bei statistischen funktionen, die auch Daten aus der Vergangenheit nutzen, wird's noch schlimmer.....

Also: Dateninhalte - ja, gerne in lokale Sprache speichern, aber alles was außen drum ist bitte auf englisch belassen!

lg
Manfred

**Comment by ciddi89** [comment]
Naja leider kann man es nicht jeden recht machen. Und es wurde sich vielfach gewünscht das die Listen auf Systemsprache sind. Das mit den Skripten sind dann eigene Baustellen wofür ich nichts kann. Aber für den Fall das jemand es doch auf English oder doch eine andere Sprache haben möchte gibt es in den Einstellungen des device watchers einen Menüpunkt wo man es sich wieder auf Englisch stellen kann. Unter 'andere Einstellungen -> Sprache'

**Comment by ciddi89** [comment]
Ansonsten sollte man soweit wie möglich die 'raw' Listen für Skripte nehmen. Die sind und bleiben auch immer komplett auf Englisch. Andere wollten die auch gerne auf deutsch/eigene Sprache haben, da ich aber weiß das viele Skripte darauf beruhen bleiben die unangetastet.

**Comment by mango1402** [comment]
Ja, da muss ich zustimmen: man kann es keinem Recht machen ;)

Ich werd mal die RAW-Liste begutachten und dann meine zusätzlichen Applikationen umstellen.
Aber dann bitte diese Liste nicht mehr 'vermurksen' ;)

lg Manfred
