### ISSUE TITLE
Blacklist for Sonoff not working

### ISSUE THREAD

**Issue by softwarecrash** [ciddi89/ioBroker.device-watcher#33]
i used it to watch my sonoff (tasmota) devices, and i have set one to the blacklist
but it comes the message that is offline
![image](https://user-images.githubusercontent.com/44615614/184026621-1d8c27ef-10b0-436a-b564-fc77c6d41ea2.png)

have i the wrong datapoint?
thanks

**Comment by ciddi89** [comment]
Please use the this datapoint
`sonoff.*.Uptime`.
[here](https://github.com/ciddi89/ioBroker.device-watcher/blob/main/docs/de/blacklist.md) you have a overview which datapoints you can use for each adapter for the blacklist.

But I have an recommendation for you. I see you have an whitespace in the name of your datapoint. This could be an problem for another adapter/scripts too.

**Comment by softwarecrash** [comment]
Ah the uptime dp, thanks.
Just an Idea, create a dropdown list or Something with all found devices to select wich devices to ignored.
