### ISSUE TITLE
Tradfri + HmIP

### ISSUE THREAD

**Issue by accessburn** [ciddi89/ioBroker.device-watcher#41]
Bitte den Tradfri-Netzwerk-Gateway und HmIP (AP) adaptieren :-)

**Comment by accessburn** [comment]
Tradfri:
Bewegungsmelder und Buttons alle gleich
![image](https://user-images.githubusercontent.com/980696/188841249-723d503f-21b4-4f78-a96c-b41485c3a423.png)

HmIP:
![image](https://user-images.githubusercontent.com/980696/188841580-bfd99b5d-d41f-427b-91a4-739eb7e47d10.png)

**Comment by ciddi89** [comment]
Tradfri ist mit drin. HMiP werde ich später oder morgen noch machen. Gibt es bei HMiP nur die  4 Datenpunkte pro device? Keine mehr für Erreichbarkeit oder rssi level?

**Comment by accessburn** [comment]
Fenstersensor:
![image](https://user-images.githubusercontent.com/980696/188872592-87e2d2e3-7277-4723-b263-157f77196c8a.png)

Temperaturdisplay:
![image](https://user-images.githubusercontent.com/980696/188872808-0032de1b-3423-43a6-8a0e-025d9048da88.png)

Auf Wunsch kann ich noch Festkörperthermometer, Beschleunigungssensor und PIR nachliefern.

**Comment by ciddi89** [comment]
Danke das reicht mir. Wenn ich Zeit habe guck ich mir das genauer an und versuche es mit einzupflegen :)

**Comment by ciddi89** [comment]
HmIp Adapter wurde mit hinzugefügt und ist bei neu Installation verfügbar. :)
