### ISSUE TITLE
WLED

### ISSUE THREAD

**Issue by skvarel** [ciddi89/ioBroker.device-watcher#42]
WLED als 'Supported adapter' wäre auch cool :)

![image](https://user-images.githubusercontent.com/1114419/188831575-c43d7370-5447-48f6-88e6-311665e5ee22.png)

**Comment by ciddi89** [comment]
I've added WLED to supported adapters. Please make a test if it's working for u.

**Comment by skvarel** [comment]
It works great !I Thanks !!

![image](https://user-images.githubusercontent.com/1114419/188868924-ffee587c-faa5-40c9-ad2c-54e23ae7c145.png)
