### ISSUE TITLE
Tado Adapter

### ISSUE THREAD

**Issue by GrayTheZebra** [ciddi89/ioBroker.device-watcher#43]
Es währe super wenn auch der Tado-Adapter abgefragt werden könnte.

**Comment by ciddi89** [comment]
Bitte Screenshot mit verfügbaren Datenpunkte eines Gerätes posten :)

**Comment by GrayTheZebra** [comment]
Leider zeigt Tado keine Prozente an, sondern nur "Normal" und "Low"

![chrome_2022-09-11_21-15-14](https://user-images.githubusercontent.com/57180524/189545111-6290c6f4-ce45-4782-a61e-071d76a93ee9.png)

**Comment by ciddi89** [comment]
Ja das wäre kein Problem. Welche Datenpunkte gibt es denn noch in connectionState?

**Comment by GrayTheZebra** [comment]
![chrome_2022-09-12_13-28-43](https://user-images.githubusercontent.com/57180524/189642522-d2493e3b-7528-415d-9556-9998c41be1ce.png)

**Comment by ciddi89** [comment]
Muss leider noch mal neh Frage stellen. Ein Datenpunkt mit der ID oder Geräte Namen oder ähnliches in der Art gibt es aber nicht oder? Leider kann ich zum Beispiel den Ordner Namen 'VA1782516224' nicht raus ziehen da dieser nicht in der common.name hinterlegt ist. Ich könnte zur Not aus dem Rooms Ordnern die Namen ziehen, ist aber doof wenn man im Raum mehrere Geräte hat, dann haben diese immer die selben Namen.

**Comment by GrayTheZebra** [comment]
Wenn es mehrere Geräte in einem Raum gibt, sieht das ganze so aus wie angehängt. Ich hoffe das hilft.

![chrome_2022-09-13_22-04-55](https://user-images.githubusercontent.com/57180524/189998781-10d54500-df01-4ee8-a0e5-53d5f9d37552.png)

**Comment by ciddi89** [comment]
Hab den Tado Adapter hinzugefügt. Wenn du den Adapter nochmal installierst sollte es mit drin sein. Falls irgendwas nicht richtig Funktioniert oder falsch ist dann einfach noch mal melden :)
