### ISSUE TITLE
Adapter meldet trotz deinstallation weiter states über telegram

### ISSUE THREAD

**Issue by softwarecrash** [ciddi89/ioBroker.device-watcher#44]
**Describe the bug**  
Ich hatte den 0.3.0 adapter installiert, da ein sonoff gerät sich gern mal abmeldet nervten die nachrichten etwas. also instanz deaktiviert, nachrichten kamen weiter, instanz und adapter gelöscht, iob neustart und nachrichten kommen immer noch.
die version 1.0.0 installiert, alles abgewählt und neu gestartet aber die nachrichten kommen weiterthin. wie bekomme ich das wieder in den griff?
das man bei dem update auf 1.0.0 den vorhergehenden vorher löschen muss hab ich leider zu spät gelesen

**Comment by ciddi89** [comment]
Dafür gibt es ja eine blacklist wo man solche Geräte hinzufügen kann. :) Das du trotz alter Instanz die neue Version installieret hast ist nicht das große Probleme, normalerweise dann noch mal die Instanz löschen und neu erstellen genügt. 

Aber nun zum Problem: Das ist wirklich sehr merkwürdig und kam bis dato auch noch bei keinem anderen vor soweit ich weiß. 

Was sagt denn die console wenn du `iobroker list instances` ausführst?

Gibt das log von iobroker noch Meldungen aus über den Adapter?

**Comment by softwarecrash** [comment]
also, ich hab zwischenzeitlich die 1.0.0 nochmal komplett runter geworfen und die 0.3 drauf in der hoffnung da ein haken rausnehmen zu können, ohne erfolg.
die 0.3 hab ich als instanz und adapter auch wieder deinstalliert. jetzt ist garnichts mehr da, auch `iobroker list instances` zeigt sie nicht an.
starte ich aber nun ein sonoff gerät neu, kommt direkt eine meldung `Sonoff Gerät: Regenwasserspeicher ist Offline` über telegram.
wenn ich den sonoff adapter neustarte kommen mal eben 20-25 nachrichten zusammen.
aktuell weis ich nicht in welcher richtung ich noch suchen könnte

**Comment by softwarecrash** [comment]
manchal sitzt der fehler vor dem bildschirm....
da hat sich in den tiefen des javascript adapters ein script aktiviert was ich mal geschrieben hatte um die geräte zu überwachen, da das eigentlich deaktiviert war hatte ich nun den adapter im verdacht, wieso auch immer das wieder aktiv war, jetzt ist ruhe.
ich werd mal die neue 1.0.0 ausgiebig testen :)
ich mach mal zu hier, danke für die zeit und entschuldigung
