### ISSUE TITLE
HmIP Geräte werden nicht gefunden

### ISSUE THREAD

**Issue by accessburn** [ciddi89/ioBroker.device-watcher#45]

**Comment by ciddi89** [comment]
sry mein Fehler. ein Buchstabe war klein geschrieben. Probier es bitte noch mal. 👍🏻

**Comment by accessburn** [comment]
Sauber, jetzt sind alle da.

Dass die HmIP-Geräte den Batteriestatus "ok" zurück geben ist so gedacht?

**Comment by accessburn** [comment]
![image](https://user-images.githubusercontent.com/980696/189386090-4dbdfef4-9f9d-4405-abb2-8c4865969dfc.png)
Das Gerät wird doppelt gelistet. Im Adapter nicht, ich besitze auch nur einen.

**Comment by ciddi89** [comment]
> Dass die HmIP-Geräte den Batteriestatus "ok" zurück geben ist so gedacht?

Ja das ist so gedacht. Wenn der Status von Datenpunkt lowbat auf false steht dann ist folglich die Batterie ok. Wenn der lowbat auf true geht dann steht da low. 

Hmm das ist merkwürdig. Irgendwo muss dort dann das Gerät noch versteckt sein mit den Datenpunkten 🤔

**Comment by ciddi89** [comment]
Wenn der nicht aktiviert ist sollte er auch nicht angezeigt werden. Ich habe im selektor 'hmip.*.rssiDeviceValue' eingetragen. Das heißt er sucht nur im Ordner hmip nach diesen Datenpunkt. Er listet aber auch nur dieses Gerät zwei mal auf? Alle anderen sind in Ordnung?  Vielleicht liegt dort irgendwo ein Datenpunkt Leiche rum, oder wir schon vorher erwähnt irgendwo ist er nochmal gelistet in irgendein Verzeichnis. 🤔

**Comment by accessburn** [comment]
Alles klar, ich geh dann mal weiter auf die Suche. Danke für deine Mühe :-)

**Comment by ciddi89** [comment]
Falls da nicht so viele Objekte verknüpft sind mit influx oder so evtl. Die Instanz stoppen, den Objekt Baum ab hmip löschen und die Instanz neu starten dann baut er die Struktur neu auf. Und sonst muss ich gucken ob ich den selector weiter eingrenze.
