### ISSUE TITLE
Aktuelle Version schmeißt warnings

### ISSUE THREAD

**Issue by dp20eic** [ciddi89/ioBroker.device-watcher#46]
**Describe the bug**  
der Adapter "device-watcher" beendet sich nach seiner Ausführung nicht (Schedule) und verursacht somit warnings im Log.

**To Reproduce**  
1. Stop oder kill den Prozess "device-watcher"
2. Starte den Adapter "device-watcher" neu, dann sieht das ganze so aus: ![ok](https://user-images.githubusercontent.com/71387331/191235279-11853173-a7db-4931-8c22-7541bba8b072.png)
3. auf das erste Scheduling warten und der Adapter sieht anschließend so aus: ![nok](https://user-images.githubusercontent.com/71387331/191235784-e8f64c92-1d0f-4d58-ad5d-8872d401259d.png)

4. es gibt zudem folgende Log Einträge: 
```
host.iobroker | 2022-09-20 12:30:08.119 | warn | instance system.adapter.device-watcher.0 already running with pid 291357
host.iobroker | 2022-09-20 12:15:04.112 | warn | instance system.adapter.device-watcher.0 already running with pid 291357
host.iobroker | 2022-09-20 11:46:43.650 | error | instance system.adapter.device-watcher.0 terminated with code 156 START_IMMEDIATELY_AFTER_STOP)
host.iobroker | 2022-09-20 11:45:04.079 | warn | instance system.adapter.device-watcher.0 already running with pid 254312
```

**Adapter Versions:**  
 - Verfügbare Version: 1.0.0
 - Installierte Version: 1.0.0

**Additional context**  
PlatformBetriebssystem:linux
Architektur:x64
Node.js:v16.17.0
NPM:8.15.0
Aktive Instanzen:33
Pfad:/opt/iobroker/
_nodeCurrent:16.17.0
_npmCurrent:8.15.0

VG
Bernd

**Comment by ciddi89** [comment]
Wenn der Adapter schon vor Version 1.0.0 installiert war, dann bitte die Instanz löschen und eine neue Instanz erstellen. Es gab ein Breaking change. Dies steht auch im Changelog. Da ich den Mode von shedule auf Daemon geändert habe ist die vorherige Instanz nicht mehr kompatibel zur neueren Version.

**Comment by dp20eic** [comment]
> Wenn der Adapter schon vor Version 1.0.0 installiert war, dann bitte die Instanz löschen und eine neue Instanz erstellen. Es gab ein Breaking change. Dies steht auch im Changelog. Da ich den Mode von shedule auf Daemon geändert habe ist die vorherige Instanz nicht mehr kompatibel zur neueren Version.

Hi,
ok, dann ist mir das beim lesen durch gerutscht :( somit erledigt.
