### ISSUE TITLE
Lupusec Adapter Integration wäre super

### ISSUE THREAD

**Issue by kimukao1** [ciddi89/ioBroker.device-watcher#47]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ciddi89** [comment]
Hi,
bitte ein Screenshot senden mit einem Beispiel Gerät. Habe zwar schon ein paar Informationen gefunden, die Daten sind aber alles älter. Wenn ich es richtig sehe sind die Geräte unter dem Ordner `devices` ? Es gibt Datenpunkte namens `battery_ok` und `rssi` richtig? Bei battery_ok scheint der State ein numerischer Wert zu sein? Welche Nummer steht für okay und Welche Nummer steht für nicht okay? Am besten einmal auf das Stift Symbol gehen und die JSON kopieren. Wichtig für mich ist der Teil mit dem mapping "1" = "Okay" [...] usw. 
Wenn ich die Daten habe, sollte es kein Problem mehr sein den Adapter mit zu implementieren. Ich danke schon mal. :)

**Comment by DEV2DEV-DE** [comment]
Ich hätte da auch starkes Interesse, da ich z.B. auch meine Zigbee-Temperatursensoren der Einfachheit halber an der EMA angelernt habe um zusätzliche Hardware zu sparen.

![image](https://user-images.githubusercontent.com/95883579/194481198-c909d910-ec4b-4806-822e-630eb5999570.png)
Und hier noch das JSON für Batterie und RSSI:
`{
  "type": "state",
  "common": {
    "type": "number",
    "role": "value",
    "read": true,
    "write": false,
    "min": 0,
    "max": 1,
    "polltime": 0,
    "name": "Temperatur Terrasse  (Batterie)",
    "states": "0:Leer;1:Okay",
    "icon": "/icons/54.png"
}`

`{
  "type": "state",
  "common": {
    "type": "number",
    "role": "value",
    "name": "Temperatur Terrasse  (Rssi)",
    "read": true,
    "write": false,
    "polltime": 0,
    "icon": "/icons/54.png"
  }`
