### ISSUE TITLE
Lupusec: offlineList bzw. -count 

### ISSUE THREAD

**Issue by DEV2DEV-DE** [ciddi89/ioBroker.device-watcher#55]
Zunächst mal: Vielen Dank für die schnelle Implementierung des Lupusec-Adapters.
Ich frage mich allerdings, wie die Liste offlineList zustande kommt.
![image](https://user-images.githubusercontent.com/95883579/194804787-62d1f239-c8f7-4f5f-8169-8a6a9f7f8703.png)
Meine Geräte sind alle online und eine Möglichkeit an "last contact" heranzukommen kann ich in den Objektdaten gar nicht erkennen.
Ich denke nicht, dass man dafür den Wert "ts" an den Datenpunkten heranziehen kann. Der dürfte lediglich den Zeitpunkt der letzten Änderung darstellen. Wenn ein Gerät aber z.B. seit Monaten fehlerfrei läuft, wird sich dieser Wert kaum ändern.
![image](https://user-images.githubusercontent.com/95883579/194805010-c008da1f-3e69-42a9-b718-fff7869d24eb.png)

Der Wert "cond_ok" kann Werte von 0 (Fehler) und 1 (OK) annehmen.

Gruß
Bernd

**Comment by ciddi89** [comment]
Hallo danke für die Rückmeldung. Das müssen wir nun leider testen welcher Datenpunkt am besten geeignet ist für die zeit Angabe. Da es kein connected/reachable Datenpunkt gibt nimmt er den Zeitstempel vom rssi wert. Ich bin davon ausgegangen das der rssi wert regelmäßig aktualisiert wird (nicht geändert!). Evtl kannst du in Erfahrung bringen und mir berichten welcher Datenpunkt sich evtl regelmäßig aktualisiert. Der zuletzt geändert Zeitstempel wäre dabei egal. Ich danke dir schon mal. 

Grüße Christian

**Comment by DEV2DEV-DE** [comment]
Also zumindest wenn "cond_ok" = 1 könnte man den DP komplett als OK ansehen und bräuchte gar keinen zusätzlichen Zeitpunkt zu ermitteln. Der DP braucht dann nicht in die Liste "offlineList" aufgenommen werden.

Wenn "cond_ok" = 0 wird's möglicherweise kompliziert.
Ein Kontaktsensor wird ja mehr oder weniger regelmäßig aktualisiert. Da könnte man den ts vom DP "status" oder "status_ex" nehmen und schauen, wann der sich zuletzt erfolgreich aktualisiert hat.
Bei Geräten wie z.B. "Sirene" wird das schwierig. Solange das System korrekt aufgesetzt ist und keine Fehlalarme aufgetreten sind, hat sich der Status einer Sirene hoffentlich zuletzt vor ziemlich langer Zeit geändert. Ich habe da gerade keine Idee, wo man dann den ts hernehmen könnte.
Im Gegenteil: Das was ich so an "ts" an meinen Datenpunkten sehen kann, ist mehr oder weniger sinnfrei.
Der Kontaktsensor der Haustüre hat heute bereits mehrfach ausgelöst. Trotzdem steht im "ts" des DP "status_ex" ein Wert 1642757166569. Das kann vorne und hinten nicht stimmen.
Vielleicht kann der Entwickler des Adapters da Licht ins Dunkel bringen https://github.com/schmupu/ioBroker.lupusec

Mir persönlich würde es reichen, wenn ein Datenpunkt nur bei "cond_ok" = 0 in die Liste aufgenommen wird. Der Zeitpunkt ist dabei eher zweitrangig.

**Comment by ciddi89** [comment]
Ok danke für die Info. Werde es später, wenn Zeit ist, es hinzufügen und wenn man dann in Experten Einstellungen beim Adapter auf -1 stellt wird der Datenpunkt für die Erreichbarkeit genutzt.

**Comment by ciddi89** [comment]
Bitte mal updaten und testen ob es nun passt. Daher in den Settings unter Expert Settings danach mal bei Lupusec auf -1 stellen.  Wegen den Zeiten kann ich wohl erstmal nichts ändern, das liegt halt am Lupusec Adapter da er die Datenpunkte scheinbar nicht aktualisiert.

**Comment by ciddi89** [comment]
Ok super. Ähm nicht bewusst. Hab aber als Hauptpfad lupusec.*.rssi, sehe aber da ist auch ein rssi Objekt. Denke die Werte werden dann doppelt rausgesucht. Werde es nachher nochmal ändern und den Hauptpfad auf ein anderes Objekt legen.

**Comment by DEV2DEV-DE** [comment]
Der richtige Pfad wäre vermutlich sowas wie "lupusec.x.devices.*", wobei die Schwierigkeit wahrscheinlich in der # der Instanz steckt. Bei mir ist es z.B. nicht die "0", sondern aufgrund eines Installationsfehlers die "1".
Bin zwar selbst Entwickler, aber JS ist jetzt nicht meine Kernkompetenz :-(
Vielleicht kann man das Durchlaufen des Baums auf die Objekte einschränken, die neben "rssi" auch ein "cond_ok" anbieten?

**Comment by ciddi89** [comment]
Ja genau, ich muss nur als Hauptpfad ein Datenpunkt nehmen den es nur einmal gibt. Das wäre in dem Fall der cond_ok. Hab es gestern nicht mehr geschafft, werde es aber heut Mittag ändern. Danach sollte hoffentlich alles wie gewünscht laufen. :)

**Comment by DEV2DEV-DE** [comment]
Nur keine Eile ... dass Du das so schnell eingebaut hast nötigt mir auch so Respekt ab.

**Comment by ciddi89** [comment]
Alles gut, es ist nur eine Zeile ändern und eine andere hinzufügen, somit hält sich der Aufwand in Grenzen! :) 

Hab es nun geändert und es sollte nun hoffentlich wie gewünscht laufen.

**Comment by DEV2DEV-DE** [comment]
Cool ... so sieht das echt gut aus. Danke!
