### ISSUE TITLE
Sonoff-Tasmota-Geräte unter Sonoff Adapter in Quality Liste?

### ISSUE THREAD

**Issue by Klaus28051967** [ciddi89/ioBroker.device-watcher#56]
Version 1.1

Bug? keine Sonoff-Tasmota-Geräte tauchen in der Quality Liste auf!

Ich weiß nicht ob das ein Bug ist , aber sollten bei Anwahl von Sonoff in der Quality Liste nicht alle Tasmota Geräte auftauchen 
mit der Anzeige der Wlan Qualität ... oder habe ich da was falsch verstanden?

Bei der Offline-Liste tauchen die Sonoff-Tasmota-Geräte mit auf!

Gruß Klaus

**Comment by ciddi89** [comment]
Evtl liegt der rssi State in einem unter Ordner? Ich glaube beim Sonoff Adapter kann man die Ordnerstruktur ändern, dazu müsste man in der Instanz Einstellung von Sonoff den Haken entfernen bei 'Objektbaum erstellen'. Dann sollten die Geräte evtl in der Liste auftauchen.

**Comment by Klaus28051967** [comment]
Hi , die Struktur für ein Gerät sieht so aus:
![image](https://user-images.githubusercontent.com/75585836/195261224-57dd30ab-73a3-483a-a376-26fdb35dfb30.png)

**Comment by ciddi89** [comment]
Ah okay ich sehe schon warum. Dir fehlt der Datenpunkt für den raw Wert vom wifi Signal. Du hast nur den Wifi_Rssi der ist schon umgerechnet. Werde es heut Mittag auf den Datenpunkt legen. Diesen scheinen alle Sonoff Geräte zu haben und ich spare mir die interne Umrechnung.

**Comment by ciddi89** [comment]
So hab jetzt den Wifi_RSSI State genommen. Nun sollten die Geräte bei dir auch in der Liste auftauchen.
