### ISSUE TITLE
Offline Zeit funktioniert nicht

### ISSUE THREAD

**Issue by micklafisch** [ciddi89/ioBroker.device-watcher#57]
**Describe the bug**  
Die Einstellung Offline Zeit wird bei einer Änderung der Werte nicht gespeichert (das Feld speichern wird nicht aktiv, wenn ein anderer Wert noch geändert wird ist zwar speichern aktiv, aber die Werte setzen sich wieder auf -1 zurück)

**To Reproduce**  
1. Go to 'Expert Settings'
2. Click on 'Offline-Zeit'

**Expected behavior**  
die Werte sollten gespeichert werden

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/44931749/196364277-b63e4d04-c1cd-4790-87c4-a9b6d3411a02.png)

**Comment by ciddi89** [comment]
Hallo,

Schon die Instanz entfernt und noch mal neu hinzugefügt? Evtl den Adapter nochmal neu installieren. Vielleicht reicht es auch schon wenn man die Instanz entfernt und den Datei Upload neu an stoßt indem man auf das Upload Symbol klickt unter Adapter / Experten Einstellungen und dann die Karte von devicewatcher umdreht, danach die Instanz neu erstellen. 

![image](https://user-images.githubusercontent.com/66088020/196414197-9d15b739-27b5-4e6d-9557-0434626d1f27.jpeg)

**Comment by micklafisch** [comment]
Hi, alles erwähnte probiert und kein Erfolg. 

Selbst wenn ich nur Shelly oder Ping auswähle steht der Wert auf -1 und Änderungen werden nicht gespeichert.

**Comment by micklafisch** [comment]
konnte es eingrenzen.... über die Controls neben den Feldern geht es nicht. Trage ich aber manuell eine Zahl in die Felder ein und gehe auf speichern, dann funktioniert das Ganze:


![image](https://user-images.githubusercontent.com/44931749/196426740-fe795f12-7d6b-4299-a41f-354382d87a42.png)

**Comment by ciddi89** [comment]
Admin Adapter und Rest vom System sind auf dem neusten Stand? Werde den Fehler sonst weiter geben müssen, da ich darauf kein Einfluss habe.

**Comment by ciddi89** [comment]
Gibt es Neuigkeiten bzgl. Des Fehlers?

**Comment by Wildbill-Z** [comment]
Bei mir bleibt die Zeit die ich eintrage zwar gespeichert, aber sie wird anscheinend komplett intern ignoriert. Wenn ich für Geräte "-1" eintrage, so funktioniert es wie gewollt, dass Geräte im Adapter als Offline gemeldet werden, sobald sie in vom jeweiligen Adapter offline gemeldet werden (z.B. Deconz oder Homematic).
Wenn ich aber eine manuelle Zeit im Adapter eintrage, zum Beispiel 180 für 3 Stunden, dann werden mir ALLE Geräte des jeweiligen Adapters sofort beim Speichern als Offline gemeldet und bleiben es auch.
Getestet mit HM-RPC und Deconz. -1 nimmt die offline-Datenpunkte des jeweiligen Adapters, manuelles Ändern meldet alle Geräte sofort als Offline.

Gruss, Jürgen

**Comment by micklafisch** [comment]
ich habe es ehrlich gesagt nicht weiter verfolgt. Hab die Zahl manuell eingetragen und fertig. Das mit den Pfeilen zur Wertesteuerung habe ich nicht weiter beachtet

**Comment by ciddi89** [comment]
@micklafisch Okay danke für die Rückmeldung. Bei einen anderen User hat es geholfen den Adapter neu zu installieren. Aber es wäre dann sowieso ein Issue für den Admin Adapter wenn dies öfters vorkommt. 

@Wildbill-Z könntest du mir vielleicht sagen was im Zeitstempel von einem HMRPC Gerät im Datenpunkt Unreach und bei Deconz im Datenpunkt reachable? Ist die Zeit beim `Zeitstempel` länger her als die eingegebene Zeit?

<img width="1360" alt="Screenshot 2022-11-06 at 11 31 33" src="https://user-images.githubusercontent.com/66088020/200165881-1ff8ee5e-f272-475e-9302-c71d0c5143c2.png">

**Comment by Wildbill-Z** [comment]
@ciddi89 OK, ich habe das eben mal gecheckt. In der Tat sind die Zeiten der Datenpunkte weitaus älter, als das, was ich eingestellt habe:
<img width="1094" alt="Bildschirm­foto 2022-11-06 um 11 39 06" src="https://user-images.githubusercontent.com/35911150/200166126-f375ad87-d016-4532-9a25-2bad143ceb4e.png">
<img width="1108" alt="Bildschirm­foto 2022-11-06 um 11 37 52" src="https://user-images.githubusercontent.com/35911150/200166132-2b1050bd-a9b7-4033-b95a-3235065e5428.png">
Komischerweise lief es aber vor dem letzten Update. Ich hatte da bei Deconz 180 eingestellt, da zwei Kühlschranksensoren sonst zu oft als offline gemeldet wurden (direkt von Deconz). Und spätestes nach 3 Stunden hatten sie sich dennoch mal gemeldet.
Warum die restlichen Geräte da keine Meldung erzeugt haben, erklärt sich mir dann zwar nicht, aber wenn Deconz oder Homematic da Datenpunkte über mehrere Tage nicht aktualisert, dann erklärt das ja nur, dass Dein Adapter macht, was er soll. Alles länger als die eingestellte Zeit melden. Oder hattest Du in einer älteren Version auf andere Datenpunkte getriggert? 
Jedenfalls brauche ich da wohl nicht komplett löschen und neu installieren oder sonst etwas ändern. Ich lasse erstmal auf "-1" und beobachte weiter.

Gruss, Jürgen

**Comment by ciddi89** [comment]
Ok danke für deine Rückmeldung. Was das angeht hatte ich nichts geändert. Aber ich habe sehr viel aufgeräumt und daher kann es jetzt vorkommen das es anders reagiert als vorher. Ich bin aktuell noch dabei heraus zu finden bei welchen Adaptern die Erreichbarkeit Datenpunkte zuverlässig umschalten. Um somit dann später das mit der Offlinezeit anders zu handhaben. So wie ich es bei Ping schon gemacht habe. Der Adapter meldet das Gerät als offline und wenn der offline status die zeit die man in meinem adapter angegeben hat überschritten hat, das das Gerät dann erst als offline gilt. Ich denke das wird in Zukunft dann zuverlässiger sein.

**Comment by Wildbill-Z** [comment]
Danke. Aus meiner Erfahrung kann ich sagen, dass bei Deconz und Homematic die Stati reachable bzw. unreach sehr zuverlässig funktionieren. Wenn ein Gerät nicht erreichbar ist, dann schaltet Deconz und auch Homematic (CCU3 alias PiVCCU3) sehr schnell (sofort) den Datenpunkt um. Bei mir für zwei Aqara-Sensoren eben etwas zu schnell. Die fangen sich nach 3-4 Stunden normalerweise immer wieder, nur hat dann Deconz bereits unrechable gemeldet. Bislang konnte ich das durch Eintragen von 180 Minuten im devicewatcher "abfangen" jetzt kommt halt immer wieder eine OFFLINE-Meldung, die kurz darauf (30-60min) wieder verschwindet, wenn der Sensor sich wieder meldet.
Ich lasse es mal so laufen und schaue, was die Zukunft bringt. :-)

Gruss, Jürgen

**Comment by ciddi89** [comment]
mit der neuen git version ist es nun so das bei Homematic und deconz die zeit erst gilt wenn der Datenpunkt offline geht. vielleicht läuft das nun besser bei dir @Wildbill-Z. Falls noch was ist dann bitte ein neues issue aufmachen. das hier schliesse ich erstmal. :)

**Comment by Wildbill-Z** [comment]
Habe von github geladen, bei deconz und hmrpc jeweils 180 eingestellt und den Adapter gestartet. Scheint nun zu passen. Keine sofortigen Meldungen, in den Objekten werden 0 Geräte offline angezeigt.
Danke.

Gruss, Jürgen

**Comment by Wildbill-Z** [comment]
@ciddi89 Kann es sei, dass das, was ich weiter oben bei Deconz gemeldet hatte und was Du dann angepasst hattest auch für Hue gilt? Ich habe hier eine widerspenstige Lampe, die immer mal wieder kurz reachable auf false setzt und gleich drauf wieder auf true. Da der device-watcher dann jeweils eine Offline- und gleich drauf eine Onlinemeldung geschickt hat, habe ich bei hue 5 min einsetzen wollen, um erst benachrichtigt zu werden, wenn auch nach 5 min noch offline ist. Nun war es aber so, dass sofort alle hue-Geräte als offline gemeldet wurden und auch blieben. Die rechable-Datenpunkte sind in der Tat vom Zeitstempel auch älter, teweilweise mehrere Stunden. Scheinbar kommt da nur ein neuer Zeitstempel/Wert, wenn auch tatsächlich eine Änderung erfolgt.
Lässt sich da was im Adapter ändern, oder muss ich das dann in einem Benachrichtigungsscript selbst abfangen, indem ich den Offline-Count in device-watcher nach 5 min nochmal abfrage und dan erst eine Nachricht schicke?

Gruss, Jürgen

**Comment by ciddi89** [comment]
@Wildbill-Z kannst du mal die GitHub version installieren und schauen ob das verhalten dann besser ist?

**Comment by Wildbill-Z** [comment]
@ciddi89 Hat leider nichts gebracht. Habe bei Hue 5min eingetragen und bekomme dann aber auch mit der aktuellen Github-Version sofort bei Adapterstart alle Hue offline gemeldet. Datenpunkte reachable sind alle true, aber deren Zeitstempel eben alle älter als die eingetragenen 5min (teilweise viele Tage, Hue ist eben zuverlässig 👍 ).

Gruss, Jürgen

**Comment by ciddi89** [comment]
ach hab falsch gelesen. einen moment

**Comment by ciddi89** [comment]
so @Wildbill-Z nochmal neu installieren. Nun sollte es klappen. Hatte Hue mit Zigbee verwechselt. aber die sind genau so zuverlässig daher lass ich das so.

**Comment by Wildbill-Z** [comment]
@ciddi89 Ja, nun scheint es zu passen. Habe bei Hue 5min eingetragen und bei Adapterstart bleibt der offline-counter auf 0. 👍 
Danke und schönen ersten Advent!

Gruss, Jürgen
