### ISSUE TITLE
Exception on instance start

### ISSUE THREAD

**Issue by TyrionWarMage** [ciddi89/ioBroker.device-watcher#66]
**Describe the bug**  
Device Watcher does not start, due to an exception. See log. Fully deterministic.

**To Reproduce**  
Directly on instance start.

**Screenshots & Logfiles**  

<html><body>

host.mediapc | 2022-11-06 13:08:32.260 | error | instance system.adapter.device-watcher.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
device-watcher.0 | 2022-11-06 13:08:31.696 | error | Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 13:08:31.696 | error | TypeError:  Cannot read properties of undefined (reading 'captureException')    at  DeviceWatcher.errorReporting  (/opt/iobroker/node_modules/iobroker.device-watcher/main.js:1823:38)     at DeviceWatcher.onReady  (/opt/iobroker/node_modules/iobroker.device-watcher/main.js:207:9)
device-watcher.0 | 2022-11-06 13:08:31.695 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 13:08:31.695 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

</body>
</html>

**Versions:**  
 - Adapter version: 2.0.1
 - JS-Controller version: 4.0.23
 - Node version: 16.18.1
 - Operating system: Ubuntu 22.04

**Comment by ciddi89** [comment]
Did you update from an earlier version? Please remove the instance, delete the adapter and install it again

**Comment by FoGBaV** [comment]
Same here - Blacklist was completly cleared - updated and blacklist recreated .. follwing shows up and stops the Instance afterwards : 



device-watcher.0 | 2022-11-06 15:55:10.015 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
device-watcher.0 | 2022-11-06 15:55:10.006 | info | terminating
device-watcher.0 | 2022-11-06 15:55:09.999 | info | cleaned everything up...
device-watcher.0 | 2022-11-06 15:55:09.984 | error | Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 15:55:09.983 | error | TypeError: Cannot read properties of undefined (reading 'captureException') at DeviceWatcher.errorReporting (/opt/iobroker/node_modules/iobroker.device-watcher/main.js:1823:38) at DeviceWatcher.onReady (/opt/iobroker/node_modules/iobroker.device-watcher/main.js:207:9)
device-watcher.0 | 2022-11-06 15:55:09.982 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 15:55:09.981 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
device-watcher.0 | 2022-11-06 15:55:09.979 | warn | Error catched and sent to Sentry, error: [[onReady]] error: Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 15:55:09.978 | warn | Error catched and sent to Sentry, error: [[main - create data of all adapter]] error: Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 15:55:09.977 | warn | Error catched and sent to Sentry, error: [[createDataOfAllAdapter]] error: Cannot read properties of undefined (reading 'de')

**Comment by FoGBaV** [comment]
Addon - seems to be someting in this options : 
Hs100, Meross, MihomeVacuum, Ping Sonoff, Yeelight

This one runs ok and starts without errors if activated : Alexa2, Ble, Shelly

**Comment by ciddi89** [comment]
Could anyone of you install the git version and tell me If it now works?

**Comment by FoGBaV** [comment]
> Could anyone of you install the git version and tell me If it now works?

Installed over existing Version with rhe new Github Version .... no Errors anymore ! Yeah ! 
Will do deper test now - but looks good !

Tjhank you so much for this great adapter ! Helps a lot !

**Comment by FoGBaV** [comment]
> Could anyone of you install the git version and tell me If it now works?

Nope - Sorry - after activating more options -> Error is back. Hunting now which option brings up the error ...

**Comment by ciddi89** [comment]
@FoGBaV ok then please activate each adapter for each self to find out which one makes the issue

**Comment by FoGBaV** [comment]
> @FoGBaV ok then please activate each adapter for each self to find out which one makes the issue

Did it - seems to be the Yeelight ... all others brings no errors ... 

On Yeelight : 



device-watcher.0 | 2022-11-06 17:13:54.933 | error | Cannot read properties of undefined (reading 'captureException')
-- | -- | -- | --
device-watcher.0 | 2022-11-06 17:13:54.932 | error | TypeError: Cannot read properties of undefined (reading 'captureException') at DeviceWatcher.errorReporting (/opt/iobroker/node_modules/iobroker.device-watcher/main.js:1818:38) at DeviceWatcher.onReady (/opt/iobroker/node_modules/iobroker.device-watcher/main.js:207:9)
device-watcher.0 | 2022-11-06 17:13:54.930 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 17:13:54.929 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
device-watcher.0 | 2022-11-06 17:13:54.926 | warn | Error catched and sent to Sentry, error: [[onReady]] error: Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 17:13:54.924 | warn | Error catched and sent to Sentry, error: [[main - create data of all adapter]] error: Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 17:13:54.921 | warn | Error catched and sent to Sentry, error: [[createDataOfAllAdapter]] error: Cannot read properties of undefined (reading 'captureException')
device-watcher.0 | 2022-11-06 17:13:54.917 | warn | Error catched and sent to Sentry, error: [[getDeviceName]] error: The id "yeelight-2.0." is invalid. Ids are not allowed to end in "."

**Comment by ciddi89** [comment]
@FoGBaV irgendwie macht er da ärger. Hast du ein screenshot von dem object baum eines yeelights gerät?

**Comment by FoGBaV** [comment]
> @FoGBaV irgendwie macht er da ärger. Hast du ein screenshot von dem object baum eines yeelights gerät?

Danke für den Tipp - das wars ! Beiden Objekten in Yeelight war ein "Ordner" komplett ohne Namen aber mit Inhalt. Hab ich gelöscht - nun kann ich auch Yeelight aktivieren. Sorry für den Aufwand  ...

Dank dir ganz sakrisch für den super Adapter ! Viele Grüße
FoGBaV

**Comment by TyrionWarMage** [comment]
@ciddi89 Mit der Git Version konnte ich nun auch bei mir den Fehler beheben. Ich hatte von 1.X nach 2.0.1 upgedated und die blacklist war fehlerhaft - leere Einträge. Löschen der Blacklist und neu Konfigurieren hat es behoben. Danke.
