### ISSUE TITLE
Zigbee Devices zeigen keine Signalstärke mehr an

### ISSUE THREAD

**Issue by dp20eic** [ciddi89/ioBroker.device-watcher#68]
Hallo,

ich bekomme die "Signalstärke" der zigbee Devices nicht mehr Angezeigt. Ich habe den Adapter, sowohl Stable als auch aktuell von github getestet.

Ich habe auch den adapter gestoppt und die Objekte gelöscht und neu anlegen lassen, Signalstärke fehlt bei den zigbee's.

Beispiel, anhand eines zigbee Tasters:
![grafik](https://user-images.githubusercontent.com/71387331/200753102-ccc5ae3f-7eb7-4c6d-8542-0d8f15c3176a.png)

Am Beispiel aus der Liste "zigbee.listAll":
```
{"Device":"DG_Schlafzimmer [Remote]","Adapter":"Zigbee","Battery":"100%","Signal strength":" - ","Last contact":"06:39 Uhr","Status":"Online"}
```

Gesamte Liste der zigbee devices.
[zigbee.listAll.zip](https://github.com/ciddi89/ioBroker.device-watcher/files/9967998/zigbee.listAll.zip)

VG
Bernd

**Comment by ciddi89** [comment]
Bitte nochmal GitHub Version testen. Sollte nun wieder angezeigt werden

**Comment by dp20eic** [comment]
Hallo Christian,

von githib installiert, Werte sind wieder da :)

Danke :+1: 

P.S.: Ein Wunsch hätte ich schon noch, Du solltest das ioBroker Wiki nicht als github nutzen, es fällt immer schwerer nachzuvollziehen wer welches Problem oder Wunsch hat. Schöner wenn es hier im Projekt als Bug oder Request for future, kommt. Dann sind die Antworten und Fragen wenigstens zusammenhängend. Die Diskussion im Wiki hat für mich schon nichts mehr mit dem Thema des Wikis zu tun. Nur mal so meine 2Cent

P.P.S: Adapter ist eine super Sache und Du hast meinen Dank und Respekt dafür.

**Comment by ciddi89** [comment]
Super freut mich. Du meinst das Forum, den Wunsch hast du nicht allein. Ich will es auch lieber das die User ein issue auf GitHub anlegen. Allein wegen der Übersicht. Ich Steig da schon selbst zwischen durch dann nicht mehr richtig durch. Hab es auch im Hauptpost als Hinweis stehen, aber naja die meisten nutzen das leider nicht.  🤷🏼‍♂️ ich danke dir aber und freue mich das du so zufrieden bist. :)
