### ISSUE TITLE
Bosch Smart Home Bridge - Support

### ISSUE THREAD

**Issue by daloki83** [ciddi89/ioBroker.device-watcher#69]
Hello,

it would be nice, if support for the Bosch devices could be added.
The datapoint have no Online or last seens status. Therefore - i think -  it should be looked for last timestamp or similar

If you need anything for this, please let me know.

**Comment by ciddi89** [comment]
Can u give me a screenshot with the datapoints and structure? Then I can see if it's possible.

thanks

**Comment by daloki83** [comment]
Yes sure, i took  a screenshot from every device...
![BoschSmartHomeController](https://user-images.githubusercontent.com/29686097/202922930-7db925af-cb9b-4763-bd47-5c4569331a95.jpg)
![Bosch-Twinguard](https://user-images.githubusercontent.com/29686097/202922933-df9f1792-2e13-45bc-8c1f-1e4cdfc50a62.jpg)
![Door-WIndows_ContactSensor](https://user-images.githubusercontent.com/29686097/202922934-894ce4dc-e90a-4bb7-9a23-9b5d1a8ed828.jpg)
![Plug](https://user-images.githubusercontent.com/29686097/202922935-69823ec8-a857-4709-b4ef-ec5390f520ed.jpg)
![SmokeDetector](https://user-images.githubusercontent.com/29686097/202922936-82edca55-264d-4fe7-a7a9-f89b1c3ebb25.jpg)

**Comment by ciddi89** [comment]
Hey sry for the late reply @daloki83,

it looks very difficult. The datapoints are not very usable for this case. But I can try to use the `batteryLevel` datapoint 'faults' and the Communication `quality` datapoint. But the type of the datapoints looks like a JSON or list format. 
- What are the values when the battery is low? 
- does the datapoints refresh regularly, especially the datapoint `fault` of batteryLevel? (the timestamp is important **not** the timestamp of last change)
- do you know other values of the datapoint `quality` except `GOOD`or `unknown`?

**Comment by daloki83** [comment]
Hi @ciddi89 
from what i can see, only the DPs for the PowerMeter will change regulary. I also asked the dev about a status DP. But so far no feedback (https://github.com/holomekc/ioBroker.bshb/issues/186).

But its possible to see the online status with the Bosch-App. So hopefully the API also supports this and it can be implemented.

![Screenshot 2022-12-17 095203](https://user-images.githubusercontent.com/29686097/208234089-122cf9f6-6e91-4c86-9e27-8964852f8657.jpg)

**Comment by warhammer73** [comment]
Hi,

the request was closed as "completed". But I cannot find the Bosch support when I'm installing the device-watcher from github.
What I'm doing wrong?


Many thanks

**Comment by ciddi89** [comment]
It was declared with ‚wontfix‘. Unfortunately i cannot work with the given data because there is no useable data. Or can you answer the questions above? Then I‘ll reopen it.
