### ISSUE TITLE
Error catched and sent to Sentry, error: [[writeDatapoints]] error: Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by Plastikman81** [ciddi89/ioBroker.device-watcher#72]
Hi,

i receive this Error in the logs:

Error catched and sent to Sentry, error: [[writeDatapoints]] error: Cannot read property 'localeCompare' of undefined

Fresh installed adapter
Plattform: linux
RAM: 7.7 GB
Node.js: v14.19.3(14.21.1 / 16.18.1)
NPM: 6.14.17(8.19.2)
Admin v6.2.23

The HTML Report will not be generated. What can i do to fix this problem?
Regards
Sebastian

**Comment by ciddi89** [comment]
Fixed with new version #fc1483f
