### ISSUE TITLE
zigbee2mqtt

### ISSUE THREAD

**Issue by MecMax** [ciddi89/ioBroker.device-watcher#82]
Hallo!
Ich würde gerne den device-watcher für meine zigbee-Geräte einsetzen. Alle meine zigbee-Geräte laufen unter zigbee2mqtt. Im ioBroker kommuniziere ich dann über MQTT-Client mit den Geräten. Funktioniert alles perfekt.
Der device-watcher findet nur die vom Adapter Ping verwalteten Geräte. Die Zibbee-Geräte findet er nicht.
Protokoll:

Hardcopy von 
![grafik](https://user-images.githubusercontent.com/80885820/205438838-ed77579f-120c-47c6-9863-248f740a0400.png)

Mache ich etwas falsch oder habe ich eine falsche Erwartungshaltung?
[Protokoll.pdf](https://github.com/ciddi89/ioBroker.device-watcher/files/10146269/Protokoll.pdf)
[iobroker.current.log.txt](https://github.com/ciddi89/ioBroker.device-watcher/files/10146270/iobroker.current.log.txt)

**Comment by ciddi89** [comment]
Hallo @MecMax Leider eine falsche Erwartungshaltung. Mit zigbee2mqtt ist der Adapter gemeint. (Noch) werden keine Geräte über mqtt erfasst.

**Comment by MecMax** [comment]
Hallo! Sehr schade. Bedeutet für mich, ich muss das anders lösen.
Trotzdem danke für die schnelle Antwort. Ich werde auf alle Fälle Deinen Adapter beobachten, vielleicht greifst Du ja noch das MQTT-Protokoll doch auf. Tausende von Iot-Sensoren usw. Kommunizieren darüber.
Noch ein schönes Wochenende.
Mfg mecmax!

**Comment by ciddi89** [comment]
@MecMax da wird auf jeden fall was kommen. 

> Tausende von Iot-Sensoren usw. Kommunizieren darüber.

Das ist halt das Problem. Und all diese Geräte haben verschiedene Datenpunkte. Daher bin ich noch am Überlegen wie ich es am besten umsetze. Es muss ja Benutzerfreundlich bleiben und Resourcenfreundlich. Daher nicht so einfach...

**Comment by MecMax** [comment]
Hallo Ciddi89!

Nur so eine Idee:

Wenn ich diese Geräte in den Aufzählungen definiere?


-- 
Mit freundlichen Grüßen

Max Mecklinger

Pfarrer-Weiß-Str. 12
86675 Buchdorf

Email: ***@***.***
Tel: +49 178 5776097

03.12.2022 19:06:35 Christian Behrends ***@***.***>:

**Comment by ciddi89** [comment]
Werde gegen Abend den Dienst zigbee2mqtt für mqtt mit einpflegen. Da es ein sehr beliebter Dienst ist, ist es denke ich sinnvoll. 

Irgendwann wird es evtl auch einen raw editor geben wo man spezielle Sachen per JSON Editor selbst mit einpflegen kann.

**Comment by ciddi89** [comment]
Ich sehe gerade du nutzt mqtt client? Was ist der unterschied zum normalen mqtt adapter? Und gibt es den Datenpunkt link_quality für die zigbee2mqtt devices?

**Comment by MecMax** [comment]
Hallo Christian!

Der normale MQTT-Adapter beinhaltet auch einen Broker. Ich nutze aber 
einen richtigen MQTT-Broker (Mosquitto) und benötige daher nur den 
MQTT-Client. Ich denke, das macht funktional für diese Aufgabe kein 
Unterschied.

Die zigbee2mqtt-Anwendung publiziert die Daten unter dem Topic 
zigbee2mqtt im MQTT-Broker. Wenn ich nun mit dem MQTT-Client diesen 
Topic abonniere, bekomme ich die Daten im iobroker so angelegt, wie von 
zigbee2mqtt publiziert.



Ich kann zigbee2mqtt so konfigurieren, dass bei jedem Gerät der 
Datenpunkt availability auftaucht (mit online oder offline als Inhalt).

Das gilt alles nur für zigbee2mqtt.

Bei meinen Tasmotageräten heisst der topic im Standard tele und der 
Datenpunkt LWT (Inhalt Online oder Offline). Diese Geräte kann ich aber 
auch mit dem Ping überprüfen:



Ich hoffe, ich konnte Dir helfen!

MfG Max

**Comment by ciddi89** [comment]
hm okay ja wichtig ist für mich der Datenpunkt availability. Dieser scheint ja bei dir aktiv zu sein. Link quality wäre gut, ist aber kein muss. Werde mir die Tage was überlegen wie ich es am besten implementiere. Daher bitte dieses issue nicht schliessen.

**Comment by ciddi89** [comment]
@MecMax MQTT-Client Zigbee2MQTT ist nun mit aufgenommen und in der GitHub Version verfügbar.
