### ISSUE TITLE
Add Synology Chat to notification service

### ISSUE THREAD

**Issue by dp20eic** [ciddi89/ioBroker.device-watcher#85]
**Describe the solution you'd like**
For the notification of offline or battery problems, you can choose which service you would like to be informed about, I would like to have the additional option Synochat, because I don't use Telegram or WhatsApp,

**Additional context**
https://github.com/phoeluga/ioBroker.synochat

with kind regards
Bernd

**Comment by Scrounger** [comment]
No stress, created the issue mainly for myself, because tracking via github is easier than in the forum ;-)

**Comment by dp20eic** [comment]
sorry, what, can't follow right now? 

⊙﹏⊙

**Comment by ciddi89** [comment]
? I can't follow you. 😬 Will add the synochat in the next days

**Comment by ciddi89** [comment]
<img width="1540" alt="Screenshot 2022-12-11 at 15 39 55" src="https://user-images.githubusercontent.com/66088020/206910605-9195f256-6e69-4cc8-b914-8b4ab204e166.png">

Added SynoChat

**Comment by dp20eic** [comment]
> <img alt="Screenshot 2022-12-11 at 15 39 55" width="1540" src="https://user-images.githubusercontent.com/66088020/206910605-9195f256-6e69-4cc8-b914-8b4ab204e166.png">
> 
> Added SynoChat

Guten Tag,
ich habe mal grob getestet, sieht gut aus.

Danke.
