### ISSUE TITLE
Feature: Notification if update available

### ISSUE THREAD

**Issue by Scrounger** [ciddi89/ioBroker.device-watcher#87]
**Describe the solution you'd like**
It would be great if the adapter would also check for updates and send a notification.
Think that actually fits great to this adapter, what do you think?

**Comment by ciddi89** [comment]
I think it's a good Idea! Thanks for it!
Please try the GitHub Version. You will find the new option under notifications.

<img width="583" alt="Screenshot 2022-12-15 at 19 05 44" src="https://user-images.githubusercontent.com/66088020/207935200-c9a81bff-e418-4597-9169-7f9a7133bab9.png">

**Comment by Scrounger** [comment]
@ciddi89 

oh great, that was fast. Thank you!
I will try it in the next days and give a feedback

**Comment by Scrounger** [comment]
@ciddi89 

It works that it detects when updates for new adapters are available.
That was not quite what I meant, sorry. I had not thought of this option. A good example why feature request should be well formulated ;-)

My idea is actually to get an info when there is e.g. a firmware update for a device.
Let's take for example a unifi device. Here there is the datapoint `unifi.0.default.devices.X.upgradable` which tells that there is a new firmware. 

The `arrApart.js` would then need a property `upgrade` for example:
```
	unifi: {
		Selektor: 'unifi.*.devices.*.uptime',
		adapterID: 'unifi',
		adapter: 'Unifi',
		battery: 'none',
		reach: '.state',
		isLowBat: 'none',
		id: 'none',
		upgrade: '.upgradable'
	},
```

What do you think?

**Comment by ciddi89** [comment]
@Scrounger ah okay yes this makes sense. I wasn't sure about it, because only a few adapter gives this information. But never mind, I think it makes sense and we can add it.

**Comment by ciddi89** [comment]
@Scrounger Okay I think it is now as you imagined it.
<img width="495" alt="Screenshot 2022-12-18 at 16 06 22" src="https://user-images.githubusercontent.com/66088020/208306999-52e8ff17-6841-49fb-8a65-447acdcebbd2.png">
![IMG_0621](https://user-images.githubusercontent.com/66088020/208307006-e7788ed5-7568-4285-acbb-a1d63dfa59a8.jpeg)

**Comment by Scrounger** [comment]
Great thanks for implementing this! Works fine.
