### ISSUE TITLE
kein Ergebnis

### ISSUE THREAD

**Issue by Ball-Pic** [ciddi89/ioBroker.device-watcher#9]
Es werden offensichtlich keine Adapter ausgelesen
Alle Listen sind leer:
[{"Device":"--keine--","Adapter":"","Battery":""}]

Es werden keine Datenpunkte aktualisiert  - ausgenommen ist lastCheck: hier wird der Timestamp eingetragen

Wenn weitere Infos benötigt werden, bitte melden

**Comment by skvarel** [comment]
@Ball-Pic .. Admin 6? Da hatte ich das Problem auch. Mit Admin 5 läuft der Adapter.

**Comment by ciddi89** [comment]
Okay würde mich auch interessieren ob da schon Admin 6 bei dir läuft? Hab es noch nicht probiert da die Beta ja erst paar Tage raus ist. Wenn nicht welche Adapter hast du in der Instanz Einstellungen gewählt? Kommt evtl eine Meldung im log?

**Comment by Ball-Pic** [comment]
Hallo
Ich verwende keine Beta-Versionen - alle Softwarekomponenten sind jedoch am letzten Stand.
Daher auch Admin5 im Einsatz
In der Instanz habe ich nicht wirklich etwas eingetragen.
Ich finde nur eine Checkbox "Option1" und einen Textfeld "Option2" vor
![image](https://user-images.githubusercontent.com/81575941/172430416-d5b5eae3-fb2e-4cd2-aa03-e099e06d7992.png)
Oder habe ich etwas überlesen, daß man hier etwas setzen muß?
Hätte angenommen, daß automatisch der zigbee-Adapter (und Sonoff?) durchsucht wird.

**Comment by Ball-Pic** [comment]
Ich bilde mir zwar ein, daß ich diesen Link für die Installation verwendet habe, deinstalliere dennoch den Adapter und verwende den Link in Deinem Kommentar.
Das Ergebnis melde ich dann in Kürze

**Comment by Ball-Pic** [comment]
Hmmmm - sehr komisch
Wenn ich Deinen Link für die Installation verwende, bekomme ich in den Instanzen (Einstellungen) wieder folgendes angezeigt:
![image](https://user-images.githubusercontent.com/81575941/172445419-2a62feda-552e-4907-9a5d-9459100293fb.png)
Der Adapter zeigt auch die Version 0.0.5 an:
![image](https://user-images.githubusercontent.com/81575941/172445630-012045c6-ec2f-4ce7-a0d7-035d22b4a85f.png)

Hast eine Idee, wie man die richtige Version installiert bekommt?
Den Adapter habe ich natürlich vorher deinstalliert....

**Comment by ciddi89** [comment]
Okay, anstatt der JSON Admin Oberfläche nimmt er die alte HTML Oberfläche. Habe dazu gestern was gelesen und habe es nun mit eingefügt. Ansonsten muss ich da mal nach haken warum das bei dir so ist.  Könntest du es bitte noch einmal probieren mit deinstallieren und neu installieren? Du benutzt aber nicht die "Alte" Benutzeroberfläche sondern die aktuelle die mit Admin 5 kam oder? Ist nur merkwürdig da es bei allen anderen noch nicht vorkam.

**Comment by ciddi89** [comment]
Habe es selbst gerade mal geprüft. Denke das du die "Alte" Benutzeroberfläche benutzt. Die unterstützt das JSON Format der neuen Oberfläche nicht.

**Comment by ciddi89** [comment]
Hast du dies in deiner Admin Instanz Einstellung Aktiviert?
<img width="1092" alt="Screenshot 2022-06-07 at 20 11 32" src="https://user-images.githubusercontent.com/66088020/172453293-868ca440-4d58-4c12-9267-51098d2a24f9.png">

**Comment by Ball-Pic** [comment]
Nein - hab' die Standardeinstellungen belassen:
![image](https://user-images.githubusercontent.com/81575941/172454413-ec4512da-62da-49cb-9129-a5c007f5a67c.png)

**Comment by Ball-Pic** [comment]
Ich habe die Option "Benutze alte Benutzeroberfläche" mal gesetzt, dann wieder weggenommen und anschließend den Adapter neu gestartet - leider...

**Comment by ciddi89** [comment]
hm okay. Musste nun selbst mal bei den anderen Devs nach rat fragen. Kannst du mal im Experten Modus bei Adapter mal beim Device-Watcher auf diesen Button den DateiUpload noch mal ankurbeln? Vielleicht dann Instanz noch mal neu starten und dann mal gucken ob die Einstellungen vorhanden sind.
<img width="321" alt="Screenshot 2022-06-07 at 21 26 50" src="https://user-images.githubusercontent.com/66088020/172466299-b1eaf490-3d41-442f-a4b0-de681464af4f.png">

**Comment by Ball-Pic** [comment]
Servus
...leider - ändert nichts....
Mit iobroker.PRO kann es nichts zu tun haben, oder?

**Comment by ciddi89** [comment]
Okay. Ne wüsste nicht warum mit Pro ein Konflikt entstehen könnte. Werde das aber mal weiter verfolgen. Aktuell bist du der einzige mit dem Problem und es sind schon über 50 Installationen im Umlauf daher ist  es wirklich strange.

**Comment by skvarel** [comment]
Mit dem Admin 6.0.2 läuft der Adapter super!

**Comment by Fredchenhh** [comment]
Muss mich leider anschließen. Habe das selbe Problem. Habe auch 0.0.6

Nur Option 1 und 2

**Comment by ciddi89** [comment]
Danke für die Meldung @Fredchenhh. Ja die alte Ansicht wird nicht unterstützt. Das liegt daran das die Einstellungsseite über json läuft und das wird da noch nicht unterstützt. Falls du nicht mit der neuen Ansicht arbeiten willst, evtl. Kurz in der neuen Ansicht die Einstellungen machen und dann wieder umstellen auf alte Ansicht. Eine andere Lösung hätte ich erstmal nicht.
