### ISSUE TITLE
Direct link to device

### ISSUE THREAD

**Issue by copystring** [ciddi89/ioBroker.device-watcher#91]
**Describe the solution you'd like**
Currently I use my own scripts which do kind of what this adapter is doing. Maybe I'll switch to the adapter to clean up things a bit.
But this adapter needs to have a list where you can directly click on a link which goes directly to the device.
See this example: 
![image](https://user-images.githubusercontent.com/1298861/208523119-cddf042e-737f-41eb-b78d-04220dd3a500.png)

The link points to http://zigbee2mqtt:8080/?#/device/0x842e14fffe01d883/info for example
Should also be possible for shelly devices with web interface and maybe other devices.

**Comment by ciddi89** [comment]
Sry for the late response. I'm thinking about how to implement this in a good and useful way for all users. Maybe I will add a checkbox to activate this feature and a textfield to add the main link/ip address to the webpage. What kind of list do you using? HTML or JSON?

**Comment by copystring** [comment]
Not sure what you mean. The screenshot above is an email I sent to myself with clickable links in html. No json. Does this answer your question?
