### ISSUE TITLE
[JsonConfig] Cannot read file: Not exists

### ISSUE THREAD

**Issue by Flyor** [ciddi89/ioBroker.device-watcher#95]
Fresh installed, this screen is everything I could see. Admin etc. @ latest. Already tried other browser and reinstallation... No changes at all. 

![image](https://user-images.githubusercontent.com/64526892/209450047-f462384d-c38a-4025-ad52-4ffea8c75e39.png)

Log (debug) is clean:
<html>
<body>

device-watcher.0 | 2022-12-24 21:16:42.059 | warn | No adapter selected. Please check the instance configuration!
-- | -- | -- | --
device-watcher.0 | 2022-12-24 21:16:42.058 | debug | Adapter device-watcher was started
device-watcher.0 | 2022-12-24 21:16:42.049 | info | starting. Version 2.1.0 in /opt/iobroker/node_modules/iobroker.device-watcher, node: v14.16.0, js-controller: 4.0.23
device-watcher.0 | 2022-12-24 21:16:41.927 | debug | Plugin sentry Initialize Plugin (enabled=true)

</body>
</html>

**Comment by ciddi89** [comment]
Please install the stable version or the GitHub version over the GitHub cat and paste the GitHub Link under custom installation. But please pay attention that not all functions working correctly in the GitHub version yet.
