### ISSUE TITLE
device-watcher Displays information where it shouldn't be

### ISSUE THREAD

**Issue by dp20eic** [ciddi89/ioBroker.device-watcher#96]
**Describe the bug**  
I have the following configuration at my test environment,
As shown, I activate Zwave but without using or have Zwave Adapter installed, but I get 3 objects shown as `zwave` devices.

**Screenshots & Logfiles** 
Adapter configuration:
![grafik](https://user-images.githubusercontent.com/71387331/209946569-be53ac50-cf98-4c1a-9114-a8dd8cf296f2.png)

And I get this `objects` at `device-watcher.0`
![grafik](https://user-images.githubusercontent.com/71387331/209946976-f3c7253f-c781-42eb-8047-8e235ab5dbd8.png)

The shown devices are from `zigbee2mqqt`, see `.json` below
```
[{"Device":"","Adapter":"Zigbee2MQTT","Battery":"100%","Status":"Online"},{"Device":"","Adapter":"Zigbee2MQTT","Battery":"100%","Status":"Online"},{"Device":"BWM","Adapter":"Zigbee2MQTT","Battery":"74%","Status":"Offline"}]
```

**Versions:**  
 - Adapter version: 2.2.1
 - JS-Controller version: 4.0.24                   
 - Node version:  v18.12.1                           
 - Operating system: arch-linux

**Additional context**  
I did the test also with my productive system, I have only the `zigbee` Adapter installed, but also activate at `device-watcher` the `zigbee2mqtt` and `zigbee2mqtt` shows the same information as `zigbee`

![grafik](https://user-images.githubusercontent.com/71387331/209948830-1bf361aa-9b6c-4956-b463-c50cdf30e3a4.png)

**Comment by ciddi89** [comment]
Hi please test the new version #2.2.2. The Adapter should work better now. 
But I will add a check if there are really such devices from the respective adapters and let create the folders only then.

**Comment by dp20eic** [comment]
> Hi please test the new version 2.2.2. The Adapter should work better now. But I will add a check if there are really such devices from the respective adapters and let create the folders only then.

Hallo,
ich habe mir die Version von Github installiert, nach den ersten checks, schein jetzt die Zuordnung zu passen.

VG
Bernd


P.S.: ich bin immer noch der Meinung, das Du dir ein Releasezyklus und die Entwicklung ins Github verlegen solltest, das Thema im Forum ist mitlerweilen nicht mehr zu gebrauchen, da sieht man nicht mehr was sind Probleme oder wünsche oder Fragen.

Meine 2 Cent Meinung :)

**Comment by ciddi89** [comment]
Hallo @dp20eic 
Ok wenn das Problem dann für dich behoben ist kann der thread geschlossen werden.

Ja ich weiss, aber leider kann ich das nicht ganz verhindern, da dort ja nun mal die meisten unterwegs sind. Versuche mir aber anzugewöhnen selber auf GitHub Issues zu erstellen. Habe mittlerweile auch ein [Projectboard](https://github.com/users/ciddi89/projects/2) erstellt. Vielleicht ist es für den ein oder anderen, vor allem für mich, übersichtlicher. :)
